getodk/briefcase

src/org/opendatakit/briefcase/ui/FormTransferTable.java

Sorry for not exactly following the contribution workflow, i´m new to contributing to OS projects.
I tackled the issue of sorting the FormTransferTable alphabetically. I basically tried to stick to the code style and used a private member class to encapsulate the logic.

Open-Issue: Sort the forms in the briefcase alphabetically #1

---

res/ODK_LICENSE.txt

Update versions in license to match versions in libs

---

src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
src/org/opendatakit/briefcase/ui/SettingsPanel.java

Moved Briefcase storage location interface to a new Settings Pane. Fix #21

Moved Briefcase storage location interface to a new Settings Pane. Fix #21

---

src/org/opendatakit/briefcase/util/AggregateUtils.java

Added description in connection error message in case protocol is not specified Fixes #24
**Before**
**After**

Added description in connection error message 

---

src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java

When the application starts, pull button was enabled. Now it's not. Pull and
push buttons switched to another tab when pressed. Now they don't.
fixes #52

push pull button fixes

---

src/org/opendatakit/briefcase/ui/FormTransferTable.java

Fixes #54 
But could someone cross check on windows pls.

Selection highlight should extend behind the Details... button #54

---

src/org/opendatakit/briefcase/ui/ServerConnectionDialog.java

ui/ServerConnectionDialog: Trim spaces in the URL entered

---

config/checkstyle/checkstyle.xml
src/org/opendatakit/briefcase/util/FindDirectoryStructure.java

Fixes checkstyle violations for single line java doc

Fixes checkstyle violations for single line java doc

---

config/checkstyle/checkstyle.xml
src/org/opendatakit/briefcase/util/AggregateUtils.java

Fixes checkstyle violations for empty catch clauses.

Fixed check-style violations for empty catch clauses.

---

src/org/opendatakit/briefcase/util/ExportToCsv.java

While exporting, if the destination folder already contains a file with the
same name, compute the MD5 hash of the files and compare them. If
same, skip copying; else append a suffix to differentiate the files.
For better performance, cache the already computed hash in a HashMap with
fileName-hashValue as key-value pair.
Fix #77

util/ExportToCsv: Only duplicate media on export when they are unique

---

src/org/opendatakit/briefcase/model/ExportProgressPercentageEvent.java
src/org/opendatakit/briefcase/ui/ExportPanel.java
src/org/opendatakit/briefcase/util/ExportToCsv.java

Display progress bars while exporting

Addition of Progress Bars in export event 

---

src/org/opendatakit/briefcase/ui/FormTransferTable.java
src/org/opendatakit/briefcase/ui/PullTransferPanel.java
src/org/opendatakit/briefcase/ui/PushTransferPanel.java

Fixes the implementation of #49 so you can't initiate pulls twice, while allowing re-initiation of previous pulls.

Fixes #152: Can not re-initiate submission pulls

---

src/org/opendatakit/briefcase/model/BriefcasePreferences.java
src/org/opendatakit/briefcase/model/FormStatus.java
src/org/opendatakit/briefcase/ui/MessageStrings.java
src/org/opendatakit/briefcase/ui/SettingsPanel.java
src/org/opendatakit/briefcase/util/DatabaseUtils.java
src/org/opendatakit/briefcase/util/ServerFetcher.java
src/org/opendatakit/briefcase/util/ServerUploader.java
src/org/opendatakit/briefcase/util/WebUtils.java
src/org/opendatakit/briefcase/util/XmlManipulationUtils.java

Improved fetch performance over high-latency connections and related changes.

Briefcase-138

---

config/checkstyle/checkstyle.xml
src/org/opendatakit/aggregate/form/XFormParameters.java
src/org/opendatakit/briefcase/ui/BriefcaseCLI.java
src/org/opendatakit/briefcase/ui/BriefcaseFolderChooser.java
src/org/opendatakit/briefcase/ui/BriefcaseStorageLocationDialog.java
src/org/opendatakit/briefcase/ui/ExportFolderChooser.java
src/org/opendatakit/briefcase/ui/ExportPanel.java
src/org/opendatakit/briefcase/ui/FormTransferTable.java
src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
src/org/opendatakit/briefcase/ui/MainFormUploaderWindow.java
src/org/opendatakit/briefcase/ui/MountedSDCardChooserDialog.java
src/org/opendatakit/briefcase/ui/ODKCollectFileChooser.java
src/org/opendatakit/briefcase/ui/ODKOptionPane.java
src/org/opendatakit/briefcase/ui/ScrollingStatusListDialog.java
src/org/opendatakit/briefcase/util/AggregateUtils.java
src/org/opendatakit/briefcase/util/ExportAction.java
src/org/opendatakit/briefcase/util/ExportToCsv.java
src/org/opendatakit/briefcase/util/FileSystemUtils.java
src/org/opendatakit/briefcase/util/FindDirectoryStructure.java
src/org/opendatakit/briefcase/util/ServerFetcher.java
src/org/opendatakit/briefcase/util/TransferFromODK.java

Hey, just a small PR to help out with the code style discrepancies. Hope this is ok, my first PR, so more than happy to do any additional edits necessary.

Conform to WhitespaceAround check

---

build.gradle

I confirmed on the ODK GA account that this ID is correct. Merging is very low risk because it's just an ID that can be changed back.

Adding ODK tracking ID

---

build.gradle
src/test/java/org/opendatakit/briefcase/model/BriefcaseAnalyticsTest.java

This is a test, and it passes.
Could break the build, but doesn’t seem to have.

Make Gradle configuration changes to support JUnit tests

---

circle.yml

I confirmed that the folder we are copying exists when the command is run locally.
This is the solution we use on the other tools.
None. It's an infrastructure thing.

Add support for test output in CircleCI

---

src/org/opendatakit/briefcase/ui/ExportPanel.java
src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
src/org/opendatakit/briefcase/ui/PullTransferPanel.java
src/org/opendatakit/briefcase/ui/PushTransferPanel.java
src/org/opendatakit/briefcase/ui/SettingsPanel.java

Closes #173 
I recommend **not squashing the commits** when merging, because the change involves a lot of prep work which makes a simple before and after comparison difficult. [The key change](https://github.com/opendatakit/briefcase/pull/178/commits/a55db73a5d5fbd07fac2e9213f2c79586d15a99a).
I have more testing to do, but if that goes well, this will be ready to merge.

Issue 173 Simplify enabling/disabling the JTabbedPane, its components, and the controls within each component

---

src/org/opendatakit/briefcase/model/BriefcaseAnalytics.java
src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
src/org/opendatakit/briefcase/ui/SettingsPanel.java

Closes #176 
I've run through the code with a debugger and checked against my GA account.
It's simple.
A malicious user may spam ODK's GA account by repeatedly toggling the checkbox.

#176 Track users' decision about GA.

---

build.gradle

Ran the app and confirmed that pulling from GAE and exporting to CSV works.
Library upgrades are a good idea.
None really.

Upgrade javarosa

---

src/org/opendatakit/aggregate/form/XFormParameters.java
src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java
src/org/opendatakit/briefcase/model/BriefcaseFormDefinition.java
src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
src/org/opendatakit/briefcase/ui/SettingsPanel.java
src/org/opendatakit/briefcase/util/CacheUtils.java
src/org/opendatakit/briefcase/util/FileSystemUtils.java
src/org/opendatakit/briefcase/util/FormCache.java
src/org/opendatakit/briefcase/util/JavaRosaParserWrapper.java
src/org/opendatakit/briefcase/util/NullFormCache.java

Closes #82 
Please see https://github.com/opendatakit/briefcase/pull/136, which this replaces.
This PR rebases on master, and makes FormCache instantiable.

Add caching to prevent form processing

---

config/checkstyle/checkstyle.xml
src/org/opendatakit/aggregate/form/XFormParameters.java
src/org/opendatakit/briefcase/model/ExportType.java
src/org/opendatakit/briefcase/ui/ExportFolderChooser.java
src/org/opendatakit/briefcase/ui/FormDefinitionFileChooser.java
src/org/opendatakit/briefcase/ui/FormTransferTable.java
src/org/opendatakit/briefcase/ui/LegacyServerConnectionDialog.java
src/org/opendatakit/briefcase/ui/PrivateKeyFileChooser.java
src/org/opendatakit/briefcase/ui/ServerConnectionDialog.java
src/org/opendatakit/briefcase/ui/TransferInProgressDialog.java
src/org/opendatakit/briefcase/util/BadFormDefinition.java
src/org/opendatakit/briefcase/util/ServerFetcher.java
src/org/opendatakit/briefcase/util/StringUtils.java
src/org/opendatakit/briefcase/util/TransferFromODK.java
src/org/opendatakit/briefcase/util/WebUtils.java
src/org/opendatakit/common/web/constants/HtmlConsts.java
src/org/opendatakit/common/web/constants/HtmlStrUtil.java

Closes #131 
All tests have been run, no content changes besides checkstyle looking for tab characters.
IntelliJ whitespace conversion used.
None.

Replace tabs with spaces, fixed checkstyle errors, checkstyle now checks for tabs.

---

build.gradle
src/org/opendatakit/briefcase/model/BriefcasePreferences.java

As requested: https://github.com/opendatakit/briefcase/pull/194#issuecomment-328941800

Change to commons-logging

---

config/checkstyle/checkstyle.xml

Partially addresses #94 
- uncommented 25 Checkstyle rules to which the code already conforms
- ran Checkstyle to check that there are no issues

Uncomment Checkstyle rules which produce no issues

---

src/org/opendatakit/briefcase/ui/PullTransferPanel.java

Closes #227 
Run it locally.
I think this is the only way.
No risk.

BRIEFCASE-227 - Default the selection to the first option (aggregate).

---

src/org/opendatakit/briefcase/ui/BriefcaseCLI.java

Closes #235 
Tested the briefcase export from command line.
I think this is the only way?
This will fix the crash issue.

BRIEFCASE-235 - Call to init briefcase cache inside the CLI.

---

README.md

I added Briefcase testing plan and information about operating systems.

Added information about operating systems and Briefcase testing plan

---

.circleci/config.yml

I think it's good that we match Collect. Consistency rules!

Tweak for consistency

---

.circleci/config.yml
README.md
build.gradle

Closes #277
I confirmed that the reports post to CircleCI and to my CodeCov URL.
I tried Coveralls and CodeClimate and both were confusing and hard to set up. CodeCov was pretty straightforward and I believe it's more maintainable.
I have not verified this works on master, but I'm hoping to merge and iterate.

CodeCov support

---

src/org/opendatakit/briefcase/ui/MessageStrings.java
src/org/opendatakit/briefcase/ui/export/ExportConfiguration.java
src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java

Verified by checking that the error message shows up on global and custom exports.

Update start end date error messages

---

src/org/opendatakit/briefcase/ui/export/components/FormsTable.java

Remove the trailing period char from some texts

---

src/org/opendatakit/briefcase/util/ServerFetcher.java
src/org/opendatakit/briefcase/util/TransferFromODK.java

Closes #296
Ran the app but could not get this particular error message. 
We are narrowly replacing just this text.
This string could be concatenated to something else and that could look funny, but that concatenation is unlikely.

Capitalize aborted

---

src/org/opendatakit/briefcase/ui/export/components/ConfigurationDialog.java
src/org/opendatakit/briefcase/ui/export/components/ConfigurationDialogForm.java
src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java
test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationDialogPageObject.java
test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationDialogTest.java
test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationDialogUnitTest.java
test/java/org/opendatakit/briefcase/ui/export/components/FakeConfigurationDialogForm.java

Closes #292 
Automated (regression) UI tests
N/A
None.

Make the clear all button be enabled only when the form is not empty

---

build.gradle

I confirmed that I can choose dates and export in macOS.

Remove unused library

---

src/org/opendatakit/briefcase/ui/ServerConnectionDialog.java

Closes #312
This PR packs the dialog to accommodate everything inside.
It also makes the fields a little bit wider and centers the dialog on screen
Manual tests
N/A
N/A

Pack connection dialog

---

src/org/opendatakit/briefcase/ui/ScrollingStatusListDialog.java

Closes #324 
Also centers the dialog on the parent window.
Manual tests
N/A
N/A

Issue 324 review status history popup

---

src/org/opendatakit/briefcase/ui/FormTransferTable.java
src/org/opendatakit/briefcase/ui/export/components/FormsTableViewModel.java

Closes #318 
This PR forces a zero-inset on buttons with icons to prevent problems on Windows
Manual tests on Linux and Win10
N/A
N/A

Issue 318 fix icon buttons on windows

---

src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java

Closes #325
Manual tests
N/A
N/A

Issue 325 Fix order of datepicker and error dialogs in the window stack

---

src/org/opendatakit/briefcase/operations/Export.java
src/org/opendatakit/briefcase/operations/ImportFromODK.java
src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java

Closes #340
Closes #341 
Closes #342
Confirmed that a script with `--pull_aggregate` can pull data from a server. 
Confirmed that a script I had with `-f` exports to the specified filename. 
Backwards compatibility and consistency are important and this is the narrowest solution to that problem.
I did not test pulling from Collect.

Fix command line

---

.github/CODE_OF_CONDUCT.md

Closes #343 
Manual testing.
-
-

Fix #343 - Add a CODE_OF_CONDUCT.md file

---

src/org/opendatakit/briefcase/ui/export/components/FormsTableViewModel.java

Closes #339
Manual test on linux, mac and win10
N/A
None

Issue 339 Change color of conf override button to green when it's not empty

---

build.gradle

Closes #348 
Tried a pull and an export.
These are minor upgrades to libraries, it should be safe.
The upgrades break something. This is why we want to do this early in the release cycle and get it tested.

Upgrade to the latest minor release of libraries

---

src/org/opendatakit/briefcase/ui/FormTransferTable.java
src/org/opendatakit/briefcase/ui/PullTransferPanel.java
src/org/opendatakit/briefcase/ui/PushTransferPanel.java

Closes #335 
Ran the software, and it worked as intended. The push button is active when there is a destination and at least one form is selected. The pull button is active when at least one form is selected. 
Instead of setting the button status based on "transferring/not transferring" I am using the number of selected forms to check if the transfer button should be active or not.
Haven't tested this code via tests.

Fix #335 - Correct the behaviour of Push/Pull button.

---

src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java
src/org/opendatakit/briefcase/ui/CharsetConverterDialog.java
src/org/opendatakit/briefcase/util/ExportToCsv.java
src/org/opendatakit/briefcase/util/FileSystemUtils.java
src/org/opendatakit/briefcase/util/FindDirectoryStructure.java
src/org/opendatakit/briefcase/util/RetrieveAvailableFormsFromServer.java
src/org/opendatakit/briefcase/util/ServerFetcher.java
src/org/opendatakit/briefcase/util/ServerUploader.java
src/org/opendatakit/briefcase/util/WebUtils.java
src/org/opendatakit/briefcase/util/XmlManipulationUtils.java

Fixes https://github.com/opendatakit/briefcase/issues/370

Remove explicit type arguments

---

src/org/opendatakit/briefcase/util/ExportToCsv.java

Closes #352 
Created two encrypted forms as mentioned in the issue.
Made entries using Collect and uploaded to the server.
Successfully exported both the forms together.
This is the simplest and probably the most efficient way of doing it. Could have made the method synchronized but that will take away the multi-threading advantage - speed.
None that I am aware of.

Fix #352 - Bulk exporting more than one encrypted form fails.

---

src/org/opendatakit/briefcase/ui/CharsetConverterDialog.java
src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
src/org/opendatakit/briefcase/ui/MainClearBriefcasePreferencesWindow.java
src/org/opendatakit/briefcase/ui/MainFormUploaderWindow.java
src/org/opendatakit/briefcase/ui/MountedSDCardChooserDialog.java
src/org/opendatakit/briefcase/ui/PullTransferPanel.java
src/org/opendatakit/briefcase/ui/PushTransferPanel.java
src/org/opendatakit/briefcase/ui/SettingsPanel.java
src/org/opendatakit/briefcase/ui/WrappedFileChooser.java
src/org/opendatakit/briefcase/util/ExportToCsv.java
src/org/opendatakit/briefcase/util/FindDirectoryStructure.java
src/org/opendatakit/briefcase/util/TransferFromODK.java

Closes #369
`./gradlew check` was successful
This improves readability and reduces verbosity.
None

Replace anonymous types with their lambda equivalent

---

test/java/org/opendatakit/briefcase/export/ExportConfigurationTest.java

I remember this from the dev call demo!

Spelling error

---

src/org/opendatakit/common/cli/Param.java

Ran the code on the command line to make sure there was white space.
Narrowest fix possible
Nope.

Add whitespace to help text

---

src/org/opendatakit/aggregate/constants/ParserConsts.java

Closes #213
It is just a small fix that don't allow anyone to instantiate the class.
I'm not sure that removing unused constants is a good idea, because I don't know the reasons, why they have been added. Nevertheless, I did it because of comment in this task

ParserConsts needs a private constructor.

---

src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.form
src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java

Closes #409 
Manually tested on Linux
None

UX clean up for overwrite existing files feature

---

src/org/opendatakit/briefcase/ui/MessageStrings.java

Closes #435 
Followed the instructions on the issue: clear prefs and run Briefcase to check the new size of the dialog.
This solution simply adds line breaks to the text.
The best solution would have been to use a `JTextPane` which wraps lines according to the container's size but there is no easy way to set the size of the dialog nor the component which is used to display the text.
None.

Issue 435 improve startup dialog

---

src/org/opendatakit/briefcase/ui/MessageStrings.java

Add even more precise language about what we are collecting and why

Clearer language about analytics

---

src/org/opendatakit/briefcase/ui/MessageStrings.java

Letting perfect be the enemy of good.

Spacing tweak

---

src/org/opendatakit/aggregate/form/XFormParameters.java
src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java
src/org/opendatakit/briefcase/model/BriefcaseFormDefinition.java
src/org/opendatakit/briefcase/model/OdkCollectFormDefinition.java

Issue #433. Get rid of versionString variable in favor of modelVersion

---

config/checkstyle/checkstyle.xml
src/org/opendatakit/aggregate/constants/ParserConsts.java
src/org/opendatakit/briefcase/model/CannotFixXMLException.java
src/org/opendatakit/briefcase/model/EndPointType.java
src/org/opendatakit/briefcase/model/ExportSucceededWithErrorsEvent.java
src/org/opendatakit/briefcase/model/ExportType.java
src/org/opendatakit/briefcase/ui/BriefcaseFolderChooser.java
src/org/opendatakit/briefcase/ui/CharsetConverterDialog.java
src/org/opendatakit/briefcase/ui/MountedSDCardChooserDialog.java
src/org/opendatakit/briefcase/ui/TransferInProgressDialog.java
src/org/opendatakit/briefcase/ui/UiStateChangeListener.java
src/org/opendatakit/briefcase/ui/reused/FontUtils.java
src/org/opendatakit/briefcase/util/BadFormDefinition.java
src/org/opendatakit/briefcase/util/FormCache.java
src/org/opendatakit/briefcase/util/FormCacheable.java
src/org/opendatakit/briefcase/util/JavaRosaParserWrapper.java
src/org/opendatakit/briefcase/util/NullFormCache.java
src/org/opendatakit/briefcase/util/StringUtils.java
src/org/opendatakit/common/web/constants/HtmlConsts.java
src/org/opendatakit/common/web/constants/HtmlStrUtil.java
test/java/org/opendatakit/common/cli/ParamTest.java

Hi all,
First, thanks so much for your incredibly detailed contributors' guide! As someone fairly new to Java (and IntelliJ) it's very much appreciated.
This commit addresses issue #371 by enabling the Indentation Checkstyle module in `config/checkstyle/checkstyle.xml`. It also standardizes indentation styles in ~15 source files to match the style in the repository's code style settings.
Closes #371 
After making the changes laid out above, I ran the `./gradlew clean checkstyleMain checkstyleTest` command and received no errors. Gradle `test` and `run` tasks also perform as expected.
I followed the procedure @ggalmazor [laid out in issue #371](https://github.com/opendatakit/briefcase/issues/371), but happy to take another crack if necessary!
None that I see - this is purely code …

Enable Indentation Checkstyle module + standardize indentation - closes #371

---

src/org/opendatakit/briefcase/ui/BriefcaseCLI.java
src/org/opendatakit/common/cli/Cli.java

Closes #379.
Searched for the old error message and updated the two files that included it. 
No other approaches considered - seemed like a straightforward error to solve.
No known risks.

Fix #379. CLI unexpected error directed to Slack.

---

src/org/opendatakit/briefcase/export/DateRange.java
src/org/opendatakit/briefcase/reused/RemoteServer.java
src/org/opendatakit/briefcase/reused/http/CommonsHttp.java
src/org/opendatakit/briefcase/reused/http/Response.java
src/org/opendatakit/briefcase/ui/export/ExportPanelForm.form
src/org/opendatakit/briefcase/ui/export/ExportPanelForm.java
src/org/opendatakit/briefcase/ui/pull/components/PullFormsTableView.java
src/org/opendatakit/briefcase/ui/push/PushPanel.java
src/org/opendatakit/briefcase/ui/push/components/PushFormsTableView.java
src/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialog.java
src/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialogForm.form
src/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialogForm.java
src/org/opendatakit/briefcase/ui/reused/source/Source.java
src/org/opendatakit/briefcase/ui/reused/source/SourcePanel.java
src/org/opendatakit/briefcase/ui/settings/SettingsPanelForm.form
src/org/opendatakit/briefcase/ui/settings/SettingsPanelForm.java
test/java/org/opendatakit/briefcase/export/DateRangeTest.java
test/java/org/opendatakit/briefcase/matchers/DialogMatchers.java
test/java/org/opendatakit/briefcase/matchers/SwingMatchers.java
test/java/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialogPageObject.java
test/java/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialogTest.java

This PR replaces #463 and it contains the changes from its feedback.
Run automated tests and manually tested the UI
N/A
Nope
Nope

Issue 366 feedback

---

src/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialog.java

I hand-tested with a real Aggregate URL, a non-existing host (timeout), and an existing host with nothing listening on the port (connection refused).
SwingWorker exists for this scenario.
No
No

Use a SwingWorker in RemoteServerDialog

---

src/org/opendatakit/briefcase/ui/pull/PullPanelForm.java
src/org/opendatakit/briefcase/ui/push/PushPanelForm.java

Closes #501
Manually tested on Ubuntu (will test on mac as well and report back)
Just copied what worked on the pull tab
Nope.
Nope.

Issue 501 Fix cancel button state before/after pulling/pushing

---

src/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialog.java
src/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialogForm.form
src/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialogForm.java
src/org/opendatakit/briefcase/ui/reused/source/Source.java
test/java/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialogPageObject.java

Closes #483 
Manually tested on Ubuntu
Verified that the correct permission is shown in pull and push tabs
Verified that the shown permissions are indeed what is needed for pulling/pushing forms
It's the narrowest change I could come with
Nope
Nope.

Add notice in RemoteServer dialog about account kinds and permissions

---

src/org/opendatakit/briefcase/ui/reused/source/SelectSourceForm.form
src/org/opendatakit/briefcase/ui/reused/source/Source.java
src/org/opendatakit/briefcase/ui/reused/source/SourcePanel.java

* Ran it on macOS and confirmed the UI
* We aren't pulling/pushing data necessarily
* Custom directory isn't as clear as what we are looking for
* Ditto with individual form
* We confuse users with the new language
* https://github.com/opendatakit/docs/issues/733

Cleaner wording on sources

---

src/org/opendatakit/briefcase/util/FormCache.java

Closes #510
Followed the instructions on the issue to verify that now it does what's expected after aborting midair a pull op with some forms successfully pulled.
Narrowest fix!
Nope.
Nope.

Issue 510 update forms on pull abort

---

src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanel.java
src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java
src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelMode.java

Closes #512 
Automated and manual tests, following instructions on the original issue and #514, which didn't quite solve the issue.
It's a narrow fix for the issue.
Nope.
Nope.

Issue 512 fix pull before toggle feedback

---

src/org/opendatakit/briefcase/reused/RemoteServer.java
src/org/opendatakit/briefcase/ui/pull/PullPanel.java
src/org/opendatakit/briefcase/ui/pull/PullPanelForm.java
src/org/opendatakit/briefcase/ui/push/PushPanel.java
src/org/opendatakit/briefcase/ui/push/PushPanelForm.java
src/org/opendatakit/briefcase/ui/reused/source/SourcePanel.java

Closes #491
Pull tab verifications, starting with clean prefs (remember passwords unset):
- Set a Pull source with an Aggregate that requires credentials. Verify that the form list is filled.
- Close and reopen Briefcase. Verify that the source is unset and the form list is empty.
- Check the remember passwords setting.
- Set a Pull source with an Aggregate that requires credentials. Verify that the form list is filled.
- Close and reopen Briefcase. Verify that the source is set and the form list is filled.
- Uncheck the remember passwords setting. Verify that nothing changes on the pull tab.
- Close and reopen Briefcase. Verify that the source is unset and the form list is empty.
- Set a Pull source with an Aggregate that doesn't require credentials. Verify that the form list is filled. …

Issue 491 review pull source saving conditions

---

src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java

A classic copy-and-paste error

Fix logger class name

---

src/org/opendatakit/briefcase/ui/pull/PullPanel.java

Closes #590 
I ran Briefcase and it started.
Edit: Testing instructions
- Ensure that "remember passwords" is enabled in the Settings tab
- Create a user for the test in Aggregate
- Configure a pull source with the Aggregate server & user credentials
- Exit Briefcase
- Revoke all granted permissions for the user in Aggregate
- Start Briefcase
Expected results:
- The version in master would write an error stacktrace in the logs and refuse to start. 
- The version from this PR should log the error and start normally. 
- The pull source should be filled in
- The forms list should be empty
It may not be, but does solve the immediate problem.
I don’t think so.

At startup, ignore failure to connect to Aggregate server that is refusing connections

---

src/org/opendatakit/briefcase/ui/export/components/ExportFormsTableView.java
src/org/opendatakit/briefcase/ui/reused/TableCustomizer.java
src/org/opendatakit/briefcase/ui/reused/transfer/TransferFormsTableView.java

Closes #610 
Enhanced border effect in windows.
Now, It looks like:
No. It only affects Windows.

Issue 610 enhanced border effect in windows

---

CONTRIBUTING.md

Closes #390
This PR doesn't bring code changes
N/A
N/A
N/A
No

Remove lint task from contributing guide

---

.github/PULL_REQUEST_TEMPLATE.md

It's a text-only change so I manually looked at the diff. It's the same change as https://github.com/opendatakit/collect/pull/2488.
Good to keep the same template across tools.
Where we've had problems in the past was with larger PRs that resulted in many different changes, some carefully considered and others that turned out to be unintentional side effects. If folks doing verification at least know what code has changed, they are more likely to identify unintended changes.
In this case, the users of the template are developers who submit pull requests. This change intends to guide those developers to provide more information on intended results of their code change and possible unexpected side effects. It also intends to help make sure we don't merge changes that break the connected …

Replace risk section with behavior changes section

---

README.md
build.gradle
docs/README.md
docs/how-to-release.md

Closes #600
This PR adds a doc with instructions on how to release a new version of Briefcase

Issue 600 Add doc with instructions on how to create a release

---

docs/how-to-release.md

Address #634 
Nothing. It's just text changes.

Grammar improvements

---

src/org/opendatakit/briefcase/ui/settings/SettingsPanel.java

Closes #675
Tested manually
This PR removes a duplicated line introduced by accident in #643 
N/A
No

Issue #675 Reload cache dialog shows twice

---

src/org/opendatakit/briefcase/operations/Export.java

Closes #684
Run the CLI help command and check that the text is OK
N/A
N/A
N/A

Issue 684 Reduce CLI export op help text

---

src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.form
src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java

Closes #686 
Manually test by launching Briefcase
N/A 
This is just an aesthetic change. No feature has changed.
Yes:

Reduce "Include GeoJSON" UI label

---

src/org/opendatakit/briefcase/util/AggregateUtils.java

Closes #702
Reproduce the scenario described in #702 and run a push operation
Verify that there's no error logged and the operation completes with success on the UI.
It's a super narrow change to conditionally do the location spoof check.
This should make Briefcase more robust in cases where the users mistakenly uses the wrong ip address to work with their Aggregate servers
No

Issue 702 Avoid checking the Location response header if the response is not an HTTP 3xx redirect

---

src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java
src/org/opendatakit/briefcase/ui/pull/PullPanel.java
src/org/opendatakit/briefcase/ui/settings/SettingsPanelForm.form
src/org/opendatakit/briefcase/ui/settings/SettingsPanelForm.java

Closes #
Nothing! I'm opening this to see if @ggalmazor is open to these changes.
* "Resume last pull" isn't very precise "Resume pull from last submission pulled" feels better to me.
* We use "clear" not clean in other parts of the app
* Remove extra words like All, Always, etc. 
* If someone is using the beta, we've changed the CLI interface. I think that's safe.
* The code variables don't match the UX. I think that's OK.

WIP: Update UI with more consistent user language

---

build.gradle

Upgrade JavaRosa dependency to the latest available version

Upgrade JavaRosa to 2.15

---

build.gradle

Honestly, I edited the file in GH. I'm letting CircleCI tell me if anything breaks, which it shouldn't.
Using v2.15.1 brings some bugfixes that feel important to have in Briefcase v1.16.2
No changes should be expected, other than extended support for xform features through the JR version update.
Nope.

Bump to JR 2.15.1

---

src/org/opendatakit/briefcase/operations/PushFormToCentral.java

Closes #775
This PR solves the issue for Central. Aggregate has been already addressed in another PR.
Test manually in my computer using the central sandbox.
This is a narrow fix that uses the same code from the push to aggregate operation.
There shouldn't be any regression risk since this change uses the same code as another PR that was tested and verified.
Yes. https://github.com/opendatakit/docs/issues/1100

Issue #775 Push all forms when form_id is not specified

---

src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
src/org/opendatakit/briefcase/ui/reused/UI.java
src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/Aggregate.java
src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/Central.java
src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/target/Aggregate.java
src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/target/Central.java

Closes #815
Please see the commit comments for details of the changes.
Not enough. It looks great on a Mac, but I’ll need help checking on other platforms.
Could someone please check that the underline is gone and that the hyperlink still works when Aggregate or Central is the source or target?
Using a ContentPane and BorderLayout seems best. 
Should have no effect.
No

815 main window resizing

---

build.gradle

Bump JR to v2.17.0

---

src/org/opendatakit/briefcase/pull/PullEvent.java

Fix compilation error that somehow got through all the checks

Fix visibility of event object member

---

src/org/opendatakit/briefcase/reused/http/CommonsHttp.java

Closes #854
run on debug, build, create jar File
this is a quick hot fix
nothing worst. 
nope

bugFix to be able to push form to aggregate 
