src/org/opendatakit/briefcase/ui/FormTransferTable.java
Removed unnecessary setForeground call to JButton that cause button label to disappear.
**Before:**
**After:**
=> Removed setForeground from Details button Fixes #25

src/org/opendatakit/briefcase/model/BriefcasePreferences.java, src/org/opendatakit/briefcase/ui/PullTransferPanel.java, src/org/opendatakit/briefcase/ui/PushTransferPanel.java
pull will now be saved as a preference.
I am not entirely sure, why GitHub is marking the entire files as changed. I tried every whitespace setting I could find, but nothing changes. My local diff also seems to be working fine. If reviewing the pull request like this is too much work, I will investigate a little more and hopefully find a solution. 
To implement the feature, I extended the functionality of the <tt>BriefcasePrefereces</tt> class, so that we are now able to manage preferences per class and not only application wide. 
The username and URL are saved as a preference after they have been successfully used to connect to a server. If an <b>Aggregate 0.9.x</b> server is used, the URL and token are saved. The preferences for Aggregate 1.0 and Aggregate 0.9.x servers are managed …
=> This resolves #22. The last successful server setting for both push and

src/org/opendatakit/briefcase/ui/ExportPanel.java, src/org/opendatakit/briefcase/ui/FormTransferTable.java, src/org/opendatakit/briefcase/ui/MainFormUploaderWindow.java, src/org/opendatakit/briefcase/ui/ScrollingStatusListDialog.java
This PR Resolves #53.
To implement this, I had to modify the <tt>ScrollingStatusListDialog</tt> to hold an instance of the form, it displays information for. This was needed, because <tt>ScrollingStatusListDialog</tt> instances have to filter out FormStatusEvents, that are <b>concurrently</b> published for different forms (e.g. when downloading multiple forms).
=> Changed the ScrollingStatusListDialog to live update.

src/org/opendatakit/briefcase/util/FindDirectoryStructure.java
Some Linux flavours use /media/username or /run/media/username as mount point instead of /media. Check if it is the case and add them.
Fix #73
=> util/FindDirectoryStructure: Add additional SDCard mount points for Linux

src/org/opendatakit/briefcase/util/ExportToCsv.java
Shift the code portion creating media folder to emitSubmissionCsv (to the case where binary data is being handled).
Fix #70
=> util/ExportToCsv: On export, only create media folder when needed

src/org/opendatakit/briefcase/util/ServerFetcher.java
When the submission file is deleted from the the instance folder. During the next pull from aggregate the submission file should be re-downloaded but master doesn't re-download the submission file.
A submission file is deleted as shown here
During the next pull it is re-downloaded as shown
so this pull request solves issue #92
=> Re-download deleted submission file during next pull from aggregate server fixes #92

src/org/opendatakit/briefcase/ui/BriefcaseStorageLocationDialog.java, src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
Fixes #87
How to test
1. Move/Rename your briefcase storage.
2. Start ODK briefcase. You will see the folder selection dialog. 
3. Press Cancel. Application should quit. Restart the briefcase dialog. You should still see the folder selection dialog
4. This time choose a proper folder and press ok. App should be enabled.
=> On the initial launch if the user press "Cancel" on briefcase storage location selection dialog, user is end up having a disabled main window #87

src/org/opendatakit/briefcase/util/DatabaseUtils.java, src/org/opendatakit/briefcase/util/FileSystemUtils.java
Fixes #149 by detecting and fixing instance tracking databases that use absolute paths. It makes them portable by using paths relative to the form directory.
=> Non-portable storage directories

src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java
Finishes the console logging cleanup by redirecting javarosa output to a file in the root of the briefcase storage directory (or the user's home directory per the normal storage dir default).
=> Fixed #155: Redirect javarosa warnings from console to log file

build.gradle, src/org/opendatakit/briefcase/model/BriefcaseAnalytics.java, src/org/opendatakit/briefcase/model/BriefcasePreferences.java, src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java, src/org/opendatakit/briefcase/ui/MessageStrings.java, src/org/opendatakit/briefcase/ui/SettingsPanel.java
Add a checkBox in the settings tab so the user can give or deny their consent to having their behaviour tracked. The setting is persisted.
Generate a UUID for each unique user. The UUID is persisted.
On startup track the following: App name (Briefcase), app version, operating system type, unique user ID.
=> #137 Add Google Analytics to Briefcase

src/org/opendatakit/briefcase/model/BriefcaseAnalytics.java, src/org/opendatakit/briefcase/model/BriefcasePreferences.java, src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java, src/test/java/org/opendatakit/briefcase/model/BriefcaseAnalyticsTest.java
Fix critical problem in original implementation: data was in fact being sent to Google even when the user unchecked the checkbox. config.setGatherStats(false) does not disable the HTTP post to Google. New approach: wrap the post with if (BriefcasePreferences.getBriefcaseTrackingConsentProperty()).
Simplify code:
- remove the unneeded singleton logic
- remove the unneeded builder pattern to create the EventHits
- remove the unneeded code to prevent trackStartup from being called more than once
I don’t know why the commits are repeated. Perhaps because I renamed the local branch. Here is the [key commit](https://github.com/opendatakit/briefcase/pull/175/commits/0851336f527b97bb78554d2a61dec2306d497c3b).
I ran in the debugger with the checkbox checked and unchecked and confirmed that the …
=> Rework Google Analytics logic, fixing critical problem

src/org/opendatakit/briefcase/ui/ExportPanel.java
This “Exporting..........” text seems to be a vestage of an earlier method of showing progress. It was being cleared (and never seen), but I recently inadvertently removed code that prevented it from ever being seen. This change removes the vestage altogether.
Closes 181
I ran with no forms and saw that the label is clear. Then I pulled a form and did an export and saw that the label changed to a success message.
It removes no longer used code.
None that I can see.
=> Remove “Exporting..........” message

src/org/opendatakit/briefcase/ui/SettingsPanel.java
I'm submitting this PR because I think opt-in is not the way to go and I want to delay that decision until the next release.
I ran the application and confirmed that the checkbox and label are not in the UI.
This is as minimal of a change as I could come up with. 
There might be an issue where developers who already have a previous build and have persisted the setting want to toggle it, but they can't because it's not in the UI.
=> Do not show Google Analytics UI

src/org/opendatakit/briefcase/util/FileSystemUtils.java, src/org/opendatakit/briefcase/util/FormCache.java, src/org/opendatakit/briefcase/util/FormCacheble.java, src/org/opendatakit/briefcase/util/NullFormCache.java
Something small I missed in the change to FormCache.
Having NullFormCache implement an interface instead of extending FormCache avoids some “faking out” which caused a cache.ser file to be written to the CWD.
=> Fix problem with cache file written to current working directory

src/org/opendatakit/briefcase/ui/BriefcaseCLI.java, src/org/opendatakit/briefcase/ui/CharsetConverterDialog.java, src/org/opendatakit/briefcase/ui/ExportPanel.java, src/org/opendatakit/briefcase/ui/MainFormUploaderWindow.java, src/org/opendatakit/briefcase/ui/ScrollingStatusListDialog.java, src/org/opendatakit/briefcase/util/ExportToCsv.java, src/org/opendatakit/briefcase/util/ServerFetcher.java, src/org/opendatakit/briefcase/util/ServerUploader.java
Closes #114 
Ran all gradlew tests and checkstyle. Tried to maintain consistency in punctuation to avoid issues with "!" ending sentences.
Separated commits for UI and util in case changes will only be applied to UI.
Potential inconsistencies in captialization or punctuation in messages.
If requested, I could make another pass through and remove all '!'s in all messages throughout the application, not just in the "Success", "Failed", "Error" messages.
=> Convert ALLCAPS messages into Sentence Case and remove '!'.

build.gradle
Closes #197 
I ran briefcase and performed a pull and push, instead of seeing the slf4j binding error message, you see log statements at level INFO and higher. I immediately used this fix to enable http components logging to diagnose and fix a threading issue (which I will report separately). 
This is the best solution because it unifies all non-JDK logging into a single logging implementation, eliminates the slf4j error message due to a missing binding and restores basic logging functionality to the application. All non-JDK logging, including that of the google analytics library, can now be managed by one logging implementation.
Routing all to JDK logging is possible, but considerably more complicated without much of a gain. It also isn't necessary for briefcase's or its most important …
=> Restore basic logging functionality

src/org/opendatakit/briefcase/model/ServerConnectionInfo.java, src/org/opendatakit/briefcase/util/AggregateUtils.java, src/org/opendatakit/briefcase/util/ServerFetcher.java, src/org/opendatakit/briefcase/util/ServerUploader.java, src/org/opendatakit/briefcase/util/WebUtils.java
Gentle reorganization cleaning up HTTP code, as mentioned in https://github.com/opendatakit/briefcase/pull/206#discussion_r141114074
Built (with checkstyle), ran and pulled from Aggregate, pushed to Aggregate. I confirmed no errors and verified all submissions were processed successfully.
This removes the possibility of sharing the http context across threads by "installing" the same reference in the thread local by calling `setHttpContext()`. It also adds javadoc comments to the code and some minor code cleanup.
I considered a more drastic cleanup, but did not want to cause more conflicts than necessary since I will not be the one resolving the conflicts myself. I also wanted to make it easy to review, so tried to keep changes minimal.
This touches code critical for pushing and pulling …
=> HTTP code cleanup #206

config/checkstyle/checkstyle.xml, src/org/opendatakit/briefcase/ui/BriefcaseCLI.java, src/org/opendatakit/common/web/constants/HtmlStrUtil.java
Small PR to partially address #94 
- uncommented OverloadMethodsDeclarationOrder rule in checkstyle.xml
- changed two classes (reported by Checkstyle) to conform to rule
- ran Checkstyle again to verify that it's happy now
Should be pretty risk-free - just changes position of two methods within its classes.
=> Conform to Checkstyle OverloadMethodsDeclarationOrder rule

src/org/opendatakit/briefcase/model/ServerConnectionInfo.java, src/org/opendatakit/briefcase/ui/MainFormUploaderWindow.java, src/org/opendatakit/briefcase/ui/PushTransferPanel.java, src/org/opendatakit/briefcase/util/AggregateUtils.java, src/org/opendatakit/briefcase/util/ServerFetcher.java
ServerConnectionInfo always sets the final boolean isOpenRosaServer to true. This change consists of the following:
Change isOpenRosaServer to always return true
Inline that method, creating always-true or always-false code.
Use automatic refactorings to remove code and if statements.
In the case of AggregateUtils, there was an incorrect error message produced when there is no WebUtils.OPEN_ROSA_VERSION_HEADER. Correct this.
Closes #225 
All changes, except the error message correction were made with IDEA automatic corrections and refactorings. I ran Briefcase and did a push and a pull. Perhaps @batkinson can review the error message change in AggregateUtils.
There’s only one way to do this.
No
=> Continue (complete?) the task of removing Aggregate 0.9.x support. 

build.gradle
Closes #203 
Application was running with both Java 7 and Java 8.
The latest version of hsqldb - 2.4.0 is not compatible with Java 7. Since we are currently supporting Java 7, we can use hsqldb - 2.3.5. This can be upgraded once we move to Java 8.
No.
=> Downgraded hsqldb to 2.3.5 to work with Java 7. Fixes #203

.circleci/config.yml, circle.yml
I have confirmed that
* The cache is saved and restored (it's mostly ~/.gradle that has the useful jars)
* The reports show up in artifacts and it has HTML that renders
* The jar shows up in artifacts and it runs on macOS
* The test results show up in test summary
This cuts build time in half, which is nice. You should squash and merge!
=> CircleCI 2 support

src/org/opendatakit/briefcase/ui/BriefcaseCLI.java
Closes #237 
Ran this command `java -jar ODK\ Briefcase\ v1.8.0-50-gb2f3f12-dirty.jar -id encrypted-form -sd ~/Desktop -ed ~/Desktop -f test1.csv -pf ~/Downloads/test.pem` in terminal with a valid and invalid pem file and the response was as expected.
CLI should not have dialogs as a way to throw exception. Hence, getting rid of dialogs and introducing CL messages is the logical solution.
No, since this is related to error logging only.
=> Fixes #237. Replaces dialogs with command line messages in CLI

build.gradle, src/org/opendatakit/briefcase/Launcher.java, src/org/opendatakit/briefcase/operations/Common.java, src/org/opendatakit/briefcase/operations/Export.java, src/org/opendatakit/briefcase/operations/ImportFromODK.java, src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java, src/org/opendatakit/briefcase/ui/BriefcaseCLI.java, src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java, src/org/opendatakit/common/cli/Args.java, src/org/opendatakit/common/cli/Cli.java, src/org/opendatakit/common/cli/CustomHelpFormatter.java, src/org/opendatakit/common/cli/Operation.java, src/org/opendatakit/common/cli/Param.java, src/org/opendatakit/common/cli/package-info.java
This is the first of a series of PRs that will try to solve current coupling problems in Briefcase between logging, command line args parsing, console command execution and console UI concerns.
Currently, there is no clear separation between what can be executed from the command line, required and optional args parsing and the rest of Briefcase's logic. The current code relies heavily on duplication, conditional blocks and comments to give readers hints of what's going on and it's intertwined in code that prepares and launches the GUI.
Although the command line args parsing is not the most pressing issue to be solved, it is the easiest to start with and it will make easier the task of decoupling the rest.
**Warning: this PR bumps the project to Java8** 
Run the "pull from Aggregate" and …
=> Add a cli adapter

src/org/opendatakit/briefcase/ui/export/FileChooser.java, src/org/opendatakit/briefcase/ui/export/NativeFileChooser.java, src/org/opendatakit/briefcase/util/FindDirectoryStructure.java
Closes #261 
I've been able to reproduce the error on a virtualized Mac.
I've been able to fix the problem, just by forcing Briefcase to use Swing's file dialog.
After confirming that this is, indeed, a fix, we should migrate other file dialogs to use the new FileChooser.
Manually tested the changes on Linux and a virtualized Mac (High Sierra)
First I thought of making a workaround by debugging what the previous file dialog returned when clicked on "Open" without selecting any item but then I tried to just force Swing's dialog and it worked. ¯\\\_(ツ)\_/¯ 
I don't think so.
=> Issue 261 file folder dialog

src/org/opendatakit/briefcase/model/BriefcasePreferences.java, src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java, src/org/opendatakit/briefcase/ui/export/ExportConfiguration.java, src/org/opendatakit/briefcase/ui/export/ExportForms.java, src/org/opendatakit/briefcase/ui/export/ExportPanel.java, src/org/opendatakit/briefcase/ui/export/ExportPanelForm.form, src/org/opendatakit/briefcase/ui/export/ExportPanelForm.java, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanel.java, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.form, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java, test/java/org/opendatakit/briefcase/model/InMemoryPreferences.java, test/java/org/opendatakit/briefcase/ui/export/ExportPanelPageObject.java, test/java/org/opendatakit/briefcase/ui/export/components/FormsTableTest.java
Partially addresses #258 
Changes on this PR solve loading and saving export configurations (default and per-form) into user preferences using `BriefcasePreferences` class.
Manual tests
N/A
None I'm aware of.
=> Issue 258 save preferences

src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.form, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java
Closes #265
After setting the location for a PEM file, the button switches to a 'Clear' button that will clear the field.
Manual tests
N/A 
None I'm aware of
=> Issue 265 clear PEM file field

src/org/opendatakit/briefcase/ui/export/ExportForms.java, src/org/opendatakit/briefcase/ui/export/components/FormsTableView.java
Fixes an issue regarding custom and default export configurations that will produce an error:
```
Exception in thread "Thread-7" java.lang.RuntimeException: Wrong export configuration
at org.opendatakit.briefcase.util.ExportAction.lambda$export$0(ExportAction.java:172)
at java.util.Optional.orElseThrow(Optional.java:290)
at org.opendatakit.briefcase.util.ExportAction.export(ExportAction.java:172)
at org.opendatakit.briefcase.ui.export.ExportPanel.lambda$export$7(ExportPanel.java:108)
at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:138 …
```
=> Fix wrong config

src/org/opendatakit/briefcase/operations/Export.java, src/org/opendatakit/briefcase/ui/export/ExportForms.java, src/org/opendatakit/briefcase/ui/export/ExportPanel.java, src/org/opendatakit/briefcase/ui/export/components/FormsTableView.java, src/org/opendatakit/briefcase/ui/export/components/FormsTableViewModel.java, test/java/org/opendatakit/briefcase/ui/export/components/FormsTableTest.java
Partially addresses #258 
This PR is built on top of #272 because it uses the Preferences saving/loading infrastructure for the Export tab
Now the forms table has a new column that will track the last export date between launches.
Export dates will be tracked while using both the GUI and CLI command.
The export date will be formatted according to the user's locale.
Manual tests
N/A
None I'm aware of
=> Issue 258 last export date

build.gradle
I confirmed that the HTML report is still there.
=> HTML is supported by default

src/org/opendatakit/briefcase/ui/export/components/ConfigurationDialogForm.java
Partially closes #291 
This PR makes the dialog wider by setting a preferred width of 350 on its fields before packing.
Manual tests
N/A
N/A
=> Make the conf panel dialog wider

src/org/opendatakit/briefcase/ui/export/components/FormsTableViewModel.java
Responding to feedback from @dcbriccetti.
Tested by running on macOS and ensuring that forms with configuration are dark gray and forms without are light gray.
=> Less code is better

test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java
This PR ignores two tests that were testing dialogs on Swing UI tests and failing on macs (an windows hosts?)
Verified on a mac that the test suite passes.
N/A
N/A
=> Ignore tests that fail on a mac

test/java/org/opendatakit/briefcase/export/ExportConfigurationTest.java
This PR fixes a test to avoid problems with windows's path separators
N/A
N/A
N/A
=> Fix tests that fail on windows

src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java
Closes #321
This PR copies the preferred size of normal fields and buttons to the datepicker's components so that they have the same size.
Manual tests on ubuntu and win10
N/A
N/A
=> Fix size of datepicker components

src/org/opendatakit/briefcase/operations/Common.java, src/org/opendatakit/briefcase/operations/Export.java, src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java
Closes #304 
This PR fixes the shortcodes for the cli args to be the same as before. The help now gives this:
```
$ java -jar build/libs/ODK\ Briefcase\ v1.8.0-209-gdf57487.jar -h
Usage: java -jar briefcase.jar <params>
Available operations:
-e,--export                         Export a form
-h,--help                           Show help
-i,--import-odk                     Import from ODK
-pa,--pull-aggregate                Pull form from an Aggregate instance
-v,--version                        Show version
Params for -e operation:
-ed,--export_directory <arg>        Export directory
-file,--export_filename <arg>       Filename for export operation
-id,--form_id <arg>                 Form ID
-sd,--storage_directory <arg>       Briefcase storage directory
(optionally) …
```
=> Fix shortcodes for cli operations

src/org/opendatakit/briefcase/ui/FormTransferTable.java, src/org/opendatakit/briefcase/ui/export/components/FormsTableViewModel.java
Closes #330
It turns out that when the button is disabled, the background color set by the cell renderer is ignored.
This PR changes the strategy from enabling/disabling buttons to changing their foreground color and conditionally launching dialogs when clicked.
**Note**: On a Mac, it will only paint the background when a button is disabled (we don't know why). This PR, at least, makes the background color of cells with buttons on selected rows consistent across the different parts of the application.
Manually tested and verified on Linux and Win10
It seems to be some kind of limitation on what Swing's capable to do on tables...
None
=> Issue 330 fix table background colors 

src/org/opendatakit/briefcase/ui/FormTransferTable.java
Closes #338
Changes the detail button's fg color when the associated form gets its status history updated
Manual tests on Linux, mac and win10
It's the smallest possible change I've been able to come up with, without having to change the design and mirroring what we're already doing on the Export tab.
None.
=> Issue 338 detail button foreground on push/pull tabs

src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java, test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelPageObject.java, test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java, test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java, test/java/org/opendatakit/briefcase/ui/export/components/FakeConfigurationPanelForm.java
Closes #323 
Built and ran the program.
It is best to disable end date till you enter start date, thus eliminating one logical error.
I tested for all possible logical scenarios that I could think of and it works.
=> Fix #323 - Add date range limit to date pickers.

src/org/opendatakit/briefcase/Launcher.java, src/org/opendatakit/briefcase/model/BriefcasePreferences.java, src/org/opendatakit/briefcase/operations/CleanPreferences.java, src/org/opendatakit/briefcase/operations/ClearPreferences.java
Closes #360
This PR add a CLI command to clean user prefs. The new command is launched with the `-c` flag (also `--clean-prefs`.
Manually tested on my linux machine
N/A
None.
=> New CLI op to clean prefs

src/org/opendatakit/briefcase/ui/CharsetConverterDialog.java, src/org/opendatakit/briefcase/ui/FormTransferTable.java, src/org/opendatakit/briefcase/util/FormCache.java
Closes #355 
Running `./gradlew clean compileJava` produces no compilation error.
1. The main point of `try-with-resources` is to make sure resources are closed, without requiring the application code to do it. 
2. For fixing the `unchecked cast` warning, I added the appropriate casts in one place and for the other place I suppressed the warnings and added the `ClassCastException` to the catch for catching any exceptions. 
No
=> Fixes all compilation warnings

src/org/opendatakit/briefcase/ui/PullTransferPanel.java, src/org/opendatakit/briefcase/util/AggregateUtils.java, src/org/opendatakit/briefcase/util/WebUtils.java
Closes #334
This PR changes the HTTP requests engine to reset any HTTP context whenever we get a 401 Not Authorized response from the servers.
This fix prevents the effects of the current coupling problems that exist between the different business operations that require HTTP interaction in Briefcase but a deeper redesign is required (as I explain on [a comment on the issue](https://github.com/opendatakit/briefcase/issues/334#issuecomment-364908421)).
This PR also fixes a previous situation where the user cancels the server connection settings dialog after having successfully pulled some forms. If the user hasn't checked the "remember passwords" setting, the forms table must be cleared because pulling again will fail (we remove the password stored in memory when opening the dialog for the …
=> Issue 334 Reset HTTP context whenever we get an 401 Not Authorized response

src/org/opendatakit/common/cli/Cli.java
Provide human-friendly error message for MissingArgumentException in CLI
Closes #380
`./gradlew check` runs successfully
None
=> Provide a human-friendly error message

build.gradle, src/org/opendatakit/briefcase/Launcher.java, src/org/opendatakit/briefcase/util/FindDirectoryStructure.java
Closes #384
This PR configures Sentry appender to tag events with runtime env and release information
Sentry configuration options are:
| Key | Description |
| --- | --- |
| `sentry.enabled` | Enables Sentry configuration (defaults to false) |
| `sentry.dsn` | Sentry client DSN |
| ~`sentry.env`~ | ~Environment (defaults to `dev`)~ |
All these keys can be overwritten with a `gradle.properties` file on the project's root directory.
Manually run Briefcase, produce a syntactic error on a form and try to export it to send events to Sentry.
Confirmed that events arrive with all the specified metadata on Sentry dashboard.
Sentry also allows to set metadata through MDC properties, but I haven't been able to get it working.
None.
=> Issue 384 Sentry metadata

src/org/opendatakit/briefcase/operations/Export.java, src/org/opendatakit/briefcase/ui/BriefcaseCLI.java, src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java, src/org/opendatakit/common/cli/Param.java, test/java/org/opendatakit/common/cli/ParamTest.java
Closes #378 
Manually ran the following two commands - 
1) java -jar ODK\ Briefcase\ v1.9.0-102-g4d7e2ff-dirty.jar -e -id all-widgets --storage_directory /home/mayank/ --export_directory /home/mayank/ODKExport/ --export_filename abcd.csv -start 2018/01/20
2) java -jar ODK\ Briefcase\ v1.9.0-102-g4d7e2ff-dirty.jar -e -id all-widgets --storage_directory /home/mayank/ --export_directory /home/mayank/ODKExport/ --export_filename abcd.csv -start 2018-01-20
Positive results for both the tests.
This way we are supporting both the date formats "/" and "-".
None that I am aware of.
=> Fix #378 - Allow yyyy/MM/dd and yyyy-MM-dd for start and end dates.

src/org/opendatakit/briefcase/Launcher.java, src/org/opendatakit/briefcase/operations/Common.java, src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java, src/org/opendatakit/briefcase/operations/PushFormToAggregate.java, src/org/opendatakit/briefcase/reused/BriefcaseException.java, src/org/opendatakit/briefcase/ui/BriefcaseCLI.java, src/org/opendatakit/briefcase/util/PushFromServerException.java, src/org/opendatakit/briefcase/util/ServerConnectionTest.java, src/org/opendatakit/briefcase/util/TransferToServer.java, src/org/opendatakit/common/cli/Cli.java
Closes #20
Manually executed the new CLI operation forcing errors (wrong form_id, wrong credentials, etc.) and actually getting some forms to my GAE instance
Manually executed `-pa` flag and veryfied that it outputs the expected messages and that exits with a non-zero status
This solution mirrors what we are currently doing for pushing forms.
This PR deprecates `-pa` flag in favor of `-plla` to be more symetric with `-psha`.
Running Briefcase with `-pa` will show a message, show help and exit with non-zero status:
```
The param -pa has been deprecated. Run Briefcase again with -plla instead
```
=> Issue 20 push from cli

src/org/opendatakit/aggregate/form/XFormParameters.java, src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java, src/org/opendatakit/briefcase/util/FileSystemUtils.java, test/java/org/opendatakit/aggregate/form/XFormParametersTest.java, test/java/org/opendatakit/briefcase/model/BriefcaseFormDefinitionTest.java, test/java/org/opendatakit/briefcase/ui/SwingTestRig.java, test/resources/org/opendatakit/aggregate/parser/test-version.tpl.xml
Closes #423 
Created new unit tests that verify the change in behavior:
- A new test that parses an XForm with different version values (null, numeric and alphanumeric)
- (collateral) A new test that shows and verifies `XFormParameters.compareTo()` method
Also installed manually a form with alphanumeric version into Briefcase's storage directory and checked that Briefcase launches and is able to export the form. This is the form I've used: 
[alphanumericversion.xml.txt](https://github.com/opendatakit/briefcase/files/1871367/alphanumericversion.xml.txt)
Tested pulling and pushing forms with alphanumeric versions from/to a Kobo server.
This is the smallest change I could think of: just avoid making any type change of the incoming version string.
None I can't think of. This change relaxes …
=> Issue 423 alphanumeric form versions

build.gradle, src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java
Closes #431
Compiled and launched Briefcase, and tried to export forms
Runs all tests
N/A
I had to remove the override of `XFormParserWithBindEnhancements.parseBind(Element e)`. It seems that it only did some efficiency tricks but it's not clear why that code was there.
=> Upgrade JR dependency to version 2.9.0

src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java, src/org/opendatakit/briefcase/model/XmlDocumentFetchException.java, src/org/opendatakit/briefcase/operations/Common.java, src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java, src/org/opendatakit/briefcase/ui/StorageLocation.java, src/org/opendatakit/briefcase/util/AggregateUtils.java, src/org/opendatakit/briefcase/util/BadXMLFixer.java, src/org/opendatakit/briefcase/util/ExportToCsv.java, src/org/opendatakit/briefcase/util/FileSystemUtils.java, src/org/opendatakit/briefcase/util/ServerFetcher.java, src/org/opendatakit/briefcase/util/ServerUploader.java, src/org/opendatakit/briefcase/util/XmlManipulationUtils.java
Closes #401
The project compiles and launches GUI.
Run all tests
This is the smallest change that solves this problem towards the next release.
The best possible solution would be to explicitly express our intent of sending error reports to Sentry. We need that to send to Sentry only actionable errors, avoiding to send errors related to the user's environment or issues with specific forms and submission files.
In the process of removing sensitive info from the errors, we have lost information that _maybe_ is valuable while debugging. I think this is a risk we can assume while we do a revision or work on a way to separate the errors that should go to Sentry from other errors.
=> Issue 401 sentry sensitive info

src/org/opendatakit/briefcase/Launcher.java, src/org/opendatakit/briefcase/model/BriefcasePreferences.java
Closes #436 
Followed instructions on the issue to clear prefs and launch Briefcase to check that:
- On a first run, the setting is on
- On consecutive runs, user's preference is used
This is the smallest change I could think of
None.
=> Issue 436 gather usage default on

src/org/opendatakit/briefcase/model/BriefcasePreferences.java, src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java, src/org/opendatakit/briefcase/ui/MessageStrings.java
Closes #444
Verification 1:
- Run the clear prefs CLI operation
- Launch Briefcase. The welcome message is shown. Accept and set a storage dir. No tracking warning is shown. Close Briefcase
- Launch Briefcase. No welcome message is shown. No tracking warning is shown.
Verification 2:
- Run the clear prefs CLI operation
- Launch the `master` version of Briefcase. The welcome message is shown. Accept and set a storage dir. Close Briefcase
- Launch Briefcase (this version). No welcome message is shown. The tracking warning is shown. Close Briefcase
- Launch Briefcase (this version). No welcome message is shown. No tracking warning is shown.
The basic solution is in https://github.com/opendatakit/briefcase/commit/ea548cca06d49f2610045498f3368e8732624855 
The rest of commits just improve …
=> Issue 444 tracking warning

src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java, src/org/opendatakit/briefcase/ui/MessageStrings.java
I clarified that the data that being collected is usage data because we don't want people to think we are collecting form data. This is the language that was used in the issue at #444.
I also added a `now` to the upgrade dialog to help explain why they are seeing the dialog.
I removed the icon because it's doesn't add much and because it is low resolution is, IMHO, distracting.
=> Improve UX on start up dialogs

src/org/opendatakit/briefcase/Launcher.java, src/org/opendatakit/briefcase/util/AggregateUtils.java
Continues work related to #401 and improves the Sentry appender to toggle it depending on the tracking consent.
- Produced an export error by tampering a submission file
- Checked that disabling the tracking consent, the events don't reach Sentry
- Checked that re-enabling the tracking consent, the events reach Sentry
Regarding the anonymization of the `ConnectTimeoutException`:
Since we don't have control of this `ConnectTimeoutException`, we only can bypass the exception's message to avoid logging the host information that comes on it.
Regarding the tracking consent:
Sentry doesn't have a global toggle but it provides a callbacks system to inspect every Event and decide if it has to reach Sentry or not.
In this case, I'm taking advantage of this callback to check the tracking pref to …
=> Issue 401 Remove sentitive info from Sentry logs

src/org/opendatakit/briefcase/Launcher.java, src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java, src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java, src/org/opendatakit/common/cli/Cli.java, src/org/opendatakit/common/cli/CustomHelpFormatter.java, src/org/opendatakit/common/cli/Operation.java, src/org/opendatakit/common/cli/Param.java
Closes #424, #451, #450, #452, and #453 
This PR introduces changes aimed to ensure we use the new CLI's features as much as possible when the fallback, legacy CLI launcher is run. This happens when the user doesn't add the new operation flags we use on the new Launcher. Specifically
- Ensure that we parse command line args once
- Ensure that the `MainBriefcaseWindow` will use the new CLI's `printHelp()` method
It's important that we use the new CLI's `printHelp()` method show because we want to help users running the legacy launcher to migrate their scripts to the new one.
Also, the new CLI's `printHelp()` method uses more relaxed settings that won't clutter text if the console is too narrow.
Run Briefcase's command line operations (both new and legacy)
Setting wider console settings on …
=> Issue 424 improve spacing on cli

src/org/opendatakit/briefcase/export/ExportForms.java, src/org/opendatakit/briefcase/model/BriefcasePreferences.java, src/org/opendatakit/briefcase/model/TransferSucceededEvent.java, src/org/opendatakit/briefcase/transfer/NewTransferAction.java, src/org/opendatakit/briefcase/ui/PullTransferPanel.java, src/org/opendatakit/briefcase/ui/export/ExportPanel.java, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelMode.java, src/org/opendatakit/briefcase/util/ITransferFromSourceAction.java, src/org/opendatakit/briefcase/util/TransferAction.java, src/org/opendatakit/briefcase/util/TransferFromODK.java, src/org/opendatakit/briefcase/util/TransferFromServer.java, src/org/opendatakit/briefcase/util/TransferToServer.java
Addresses first part of #455
Manually tested:
- Send a submission from Collect to Aggregate
- Pull it with Briefcase (with "remember passwords" enabled)
- Check that exporting the form with the "pull before export" enabled works as expected
- Pull the same form from a custom ODK dir
- Check that no errors are logged in the output or log files
- Check that now Briefcase asks to pull the form from Aggregate to be able to "pull before export"
This is the narrowest fix without changing the design I could come up with. A change of design would be recommended, as discussed in #455
Nope.
Nope.
=> Issue 455 bug pulling from odk

build.gradle, src/org/opendatakit/briefcase/operations/PushFormToAggregate.java, src/org/opendatakit/briefcase/push/RemoteServer.java, src/org/opendatakit/briefcase/reused/http/CommonsHttp.java, src/org/opendatakit/briefcase/reused/http/Credentials.java, src/org/opendatakit/briefcase/reused/http/Http.java, src/org/opendatakit/briefcase/reused/http/Query.java, src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java, src/org/opendatakit/briefcase/ui/PushTransferPanel.java, src/org/opendatakit/briefcase/util/ServerUploader.java, src/org/opendatakit/briefcase/util/TransferAction.java, src/org/opendatakit/briefcase/util/TransferToServer.java, src/org/opendatakit/briefcase/util/UploadToServer.java, test/java/org/opendatakit/briefcase/push/RemoteServerTest.java, test/java/org/opendatakit/briefcase/reused/http/CommonsHttpTest.java, test/java/org/opendatakit/briefcase/reused/http/FakeHttp.java
Addresses #442:
- Avoid sending the blank form if Briefcase detects that it's already present in the destination server
- Add a new CLI flag to let users decide if they want to force sending the form anyway
While we implement the rest of #442, which involves changes on the GUI, pushing from it always sends the blank forms.
- Added tests (unit and integration) for the HTTP interaction parts
- Manually tested the CLI and GUI to verify the intended behavior:
- CLI outputs some message telling if it's sending the blank form or skipping it. Just run the CLI op with and without the `-fsb` flag
- GUI should add the same lines as the CLI to the push details when used in combination with `-fsb`
Most of the changes in this PR are quite straightforward but I had to choose between using the existing …
=> Issue 442 improve cli push

src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
Closes #490
Clear prefs, remove storage dir and run Briefcase. Check that the welcome message is shown and all the tabs are locked except for the settings tab
Just lost the line in some merge
Nope.
Nope.
=> Issue 490 Lock UI on first launch

src/org/opendatakit/briefcase/export/ExportConfiguration.java
Closes #496
Manually tested that the export button gets enabled when choosing the same date in the start and end filter fields.
This is a quite straightforward fix to ensure that the date ranges work the way we want.
Nope.
Nope.
=> Fix date range validation to allow start & date to be the same

src/org/opendatakit/briefcase/reused/RemoteServer.java
Closes #492
Manually tested UI and CLI push operations to verify that:
- The UI, it always pushes the blank form
- The CLI, it only pushes the blank form if the form doesn't exist or when `-fsb` is used
This is just a change to rescue the pattern fix, lost while merging branches. The previous pattern works when no JR headers are sent with the form list request.
Nope.
Nope.
=> Fix pattern to check if form exists on remote server

src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java, src/org/opendatakit/briefcase/ui/pull/PullPanel.java, src/org/opendatakit/briefcase/ui/push/PushPanel.java
Closes #493
Compiled and run Briefcase.
Debugged to ensure analytics code was exercised when entering/leaving tabs
This is just code that was lost on some merge
Nope.
Nope
=> Issue 493 Restore lost analytics tracking of pull/push tabs

src/org/opendatakit/briefcase/export/ExportEvent.java, src/org/opendatakit/briefcase/export/ExportToCsv.java, src/org/opendatakit/briefcase/export/SubmissionParser.java, src/org/opendatakit/briefcase/ui/reused/source/SelectSourceForm.java
This PR improves error handling of the export process
- By separating the generation of CSV lines from the writing of those lines in files, we can control any parsing/mapping problem and react by gracefully ignoring the error and logging/sending feedback events
- Parsing errors can happen while trying to read submission dates. Those submissions must be skipped and reported as individual failures
- We should prevent the export process from failing due to errors while parsing/mapping individual submissions
Before this, any parsing error would stop the export and show a cryptic error dialog to the user.
Tampered an individual submission to produce xml syntax errors and exported it.
Checked that:
- the tampered submission is not present in the output.
- other submissions are present in the …
=> Improve error handling of the export process

src/org/opendatakit/briefcase/ui/export/ExportPanel.java, src/org/opendatakit/briefcase/ui/export/ExportPanelForm.java, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanel.java, test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelPageObject.java, test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java
- Now it stays disabled after exporting if the remember passwords setting is not checked
- Now it is unchecked if the user revokes the consent to remember passwords to avoid seeing it checked and disabled
Closes #512
Manually tested in the UI
Passing the preference downstream is the narrowest fix I can come up with.
Nope.
Nope.
=> Issue 512 Fix remember passwords checkbox behavior

src/org/opendatakit/briefcase/ui/reused/Analytics.java
We were having trouble verifying that the usage information was being sent to GA, mainly because we weren't filling some fields that one would normally fill if the app was a website (following the recommendation on the GA manuals).
This PR sets the document path and title to the tab the user opens to trick GA into thinking that the app is a website. This improves a lot the information available on GA about Briefcase usage.
Previously we were even having trouble seen realtime usage information, which on this PR seems to work better.
Manually launched Briefcase and verified on GA that we are sending data.
No other option for the moment.
Nope
Nope
=> Improve data sent to analytics to track it more easily

src/org/opendatakit/briefcase/ui/settings/SettingsPanel.java, src/org/opendatakit/briefcase/ui/settings/SettingsPanelForm.java
Closes #509
Manually tested that the fields do what's expected.
Also verified that information is still saved between launches and the proxy fields are shown in the correct state,
Narrowest change
Nope.
Nope.
=> Issue 509 Fix the behavior of http proxy fields on settings tab

src/org/opendatakit/briefcase/export/ExportToCsv.java
Closes #511 
Clear preferences and launch Briefcase
Export twice the same form, verify there are double lines in the output file.
This PR just fixes the default value for that param.
Nope.
Nope.
=> Fix the default value of the overwrite files conf param

src/org/opendatakit/briefcase/export/ExportEvent.java, src/org/opendatakit/briefcase/ui/export/ExportPanel.java, src/org/opendatakit/briefcase/ui/pull/PullPanel.java, src/org/opendatakit/briefcase/ui/push/PushPanel.java
Manually pulled/pushed/exported forms to see event hits in the realtime report in GA
This is just some code that was missed during some merge conflict resolution
Nope.
Nope.
=> Fix (recover) missing pull/push/export operation GA events

src/org/opendatakit/briefcase/reused/RemoteServer.java
Closes #524
Tested getting the form list for pulling with the same Aggregate server that the user from this forum post was having problems with.
This is a narrow fix to remove a dupe header
Nope.
Nope.
=> Remove a dupe openrosa header sent

res/logback.xml.example-release
Partially addresses #522 
Run Brierfcase activating the new appender and verified that the `briefcase.log` file was generated.
Changed date and verified that the file rolling policy worked as expected (generates one file per day).
This is the rolling file appender config explained in logback docs
Nope.
Nope.
=> Add a rolling file appender to a logback conf example

src/org/opendatakit/briefcase/ui/settings/SettingsPanelForm.java
Closes #532
Manually test the form's behavior by leaving the HTTP Proxy host field empty.
Verify that there are no errors logged.
Verify that after closing and reopening Briefcase, the HTTP Proxy has not been saved
This is the smallest solution to the issue.
I opted not to give feedback by popping an error dialog because Briefcase wasn't saving anything anyway and it felt too intrusive.
Nope
Nope
=> Issue 532 improve http proxy form fields

docs/export-format.md
This PR adds a documentation file with information about the CSV format Briefcase uses to export submissions.
=> Document the export CSV format

src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
Closes #504
Set the conditions that would produce an error by moving the already saved briefcase dir location to somewhere else and run Briefcase. Verified that I got the welcome message and no errors, as expected.
This is the narrowest fix to implement a solution discussed in #504 
Nope.
Nope.
=> Issue 504 recover from moved storage dir failure

src/org/opendatakit/briefcase/export/Submission.java, src/org/opendatakit/briefcase/reused/UncheckedFiles.java, test/java/org/opendatakit/briefcase/reused/UncheckedFilesIsInstanceDirTest.java
Closes #544
This PR changes the filter Briefcase uses when listing the contents of the instances folder of a form to retrieve the submissions to be exported. Before this change, we would expect a particular format that would leave out forms using arbitrary instanceIDs and forms pulled from ODK Collect directories.
Now, the filter will reject only non-directory entries and hidden directories (directories starting with a `.` character are hidden in mac and linux computers)
- Pull a form with submissions from an ODK Collect directory and export it. 
- Artificially add a `.DS_Store` directory inside the instances folder of the pulled form and add an empty `submission.xml` file in it.
- Verify that all submissions are present and no errors are logged
I've also improved the unit test suite that …
=> Issue 544 make submissions directory filter less restrictive

src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
Closes #546
This PR fixes the time of subscription to events
- We need to wait until the UI can react (lock/unlock).
- Otherwise, it could produce NPEs since not all members of the class have been created.
This is a precaution to avoid possible NPEs. We have already received Sentry reports of this but it's quite difficult to reproduce in a controlled setup.
At least I've tried to trigger the same scenario that would produce a race between the `MainBriefcaseWindow` constructor and its event handlers to verify that no error is produced.
I've also run Briefcase and verified that the locking/unlocking system works by clearing the storage directory in the Settings tab.
This is a straightforward change.
Nope.
Nope.
=> Issue 546 Avoid NPE on main window

src/org/opendatakit/briefcase/model/BriefcasePreferences.java, src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java, src/org/opendatakit/briefcase/transfer/NewTransferAction.java, src/org/opendatakit/briefcase/ui/BriefcaseCLI.java, src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java, src/org/opendatakit/briefcase/ui/export/ExportPanel.java, src/org/opendatakit/briefcase/ui/pull/PullPanel.java, src/org/opendatakit/briefcase/ui/reused/source/Source.java, src/org/opendatakit/briefcase/util/ServerFetcher.java, src/org/opendatakit/briefcase/util/TransferAction.java, src/org/opendatakit/briefcase/util/TransferFromServer.java
Closes #398
This PR adds a new CLI param `-pp` or `--parallel_pull` to enable pulling forms in parallel on the CLI. Before this, the CLI would use whatever saved preference the user would have set using the UI's Settings tab.
This PR also changes UI code to decouple it from global state - which was harmful in many ways - wherever we needed to know if the "pull in parallel" setting was set or not.
Pulled a form with the UI with pull in parallel setting checked and unchecked. Verified on the logs that Briefcase would only use 1 thread if unchecked.
Pulled a form with the CLI adding and omitting the new `-pp` flag. Verified on the logs that Briefcase would only use 1 thread if the flag was omitted.
This a pretty straightforward change: break coupling to global state by replacing it with …
=> Issue 398 cli pull in parallel

src/org/opendatakit/briefcase/reused/UncheckedFiles.java, src/org/opendatakit/briefcase/util/FormCache.java
Closes #551
It's not clear how to reproduce this issue. On Linux, creating a `.DS_Store` won't produce any error (maybe it's dependant on system and jvm version).
Nevertheless, before this PR, directories that weren't form dirs where implicitly being filtered out by the `foreach` block's code. Now an explicit filter is taking care of it, making the whole process more clear to new eyes.
This PR also forces an update of the cache after the cache file is created in the `FormCache` file. This will let Briefcase recover from situations where the cache file has been removed by the user or it has somehow become corrupt.
Tested on Linux by creating a `.DS_Store` dir inside the `forms` dir and removing the cache file. Verified that no errors were present on the logs and that all forms in the …
=> Issue 551 ignore hidden dirs updating cache

src/org/opendatakit/briefcase/operations/Common.java, src/org/opendatakit/briefcase/operations/Export.java, src/org/opendatakit/briefcase/operations/ImportFromODK.java, src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java, src/org/opendatakit/briefcase/operations/PushFormToAggregate.java, src/org/opendatakit/briefcase/reused/UncheckedFiles.java, src/org/opendatakit/briefcase/ui/settings/SettingsPanel.java, src/org/opendatakit/briefcase/util/FormCache.java
Closes #553, closes #547 
This PR should be considered as an alternative behavior to the one proposed in  #549
Thir PR will imitate the old Briefcase behavior that will create the storage dir if the user adds a `-sd` arg that will produce a briefcase dir that doesn't exist.
Run all 4 CLI ops with an `-sd` arg that would produce a non-existent briefcase dir. Verify that user gets an error feedback message but the op completes. Verify that the briefcase dir exists afterward.
This is an alternative to failing, which is proposed in #549 
This also is what Briefcase actually did in <=1.9.0
Nope.
Nope.
=> Issue 553 make cli less picky about storage dir

test/java/org/opendatakit/briefcase/reused/UncheckedFilesIsInstanceDirTest.java
Address #545
.DS_Store is a file on a Mac, not a directory. Calling the hidden directory .DS_Store seems like a bad idea.
Ran ` ./gradlew test`
Very narrow fix.
If the test is meant to test how Briefcase works with .DS_Store **files**, then this test does not do that.
=> Making it a .DS_Store a directory could have unintended consequences

src/org/opendatakit/briefcase/reused/http/CommonsHttp.java, src/org/opendatakit/briefcase/util/WebUtils.java
Closes #557
This PR doesn't change behavior.
This PR introduces a technical change that will avoid warnings when dealing with Aggregate and compatible server that use latest RFC-compliant cookies.
Since I haven't access to a server that uses such cookies, I have tried to pull from a standard Aggregate server and I've verified that it works as expected. No errors.
The changes have been made following instructions to solve this problem that are specific of the library we're using for HTTP interaction. It's a straightforward change.
Nope.
Nope.
=> Issue 557 Use standard cookies spec

src/org/opendatakit/briefcase/export/ExportConfiguration.java, src/org/opendatakit/briefcase/export/ExportToCsv.java, src/org/opendatakit/briefcase/operations/Export.java, src/org/opendatakit/briefcase/ui/export/ExportPanel.java, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanel.java, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.form, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java, test/java/org/opendatakit/briefcase/export/ExportToCsvScenario.java
Closes #413 
Tests passing.
Tested all combinations of the new setting with the UI, both as default and override confs. Verified that media files are exported only when the option is checked.
Verified that the export media checkbox is checked by default after cleaning prefs.
Verified that the export media checkbox state was saved after relaunching Briefcase (both default and override).
The changes on this PR imitate what's being done with other conf params.
We should refactor the export conf object and related UI components to use a more up-to-date approach like in the pull/push tabs that would dramatically reduce code duplication and complexity.
Nope.
Nope.
=> Issue 413 ui disable export media

src/org/opendatakit/briefcase/Launcher.java, src/org/opendatakit/common/cli/Cli.java
Closes #530
This PR doesn't change behavior
This PR makes some technical changes to silence some of the reports that get to Sentry. Now, only non-caught exceptions that reach the Launcher (topmost class) should be sent as an error report to Sentry.
Verified that CLI ops and UI launch work as expected.
Introduced a syntactic error in a submission to produce an export error and verified that the error was logged but no error reports were sent to Sentry (it is caught and handled by the Export panel).
Forced a non-caught error by adding `throw new RuntimeException("cocotero")` to the last line on the `try` block of the `Cli.run()` method and verified that an error report was sent to Sentry (tracking consent must be checked in the Settings Tab).
This solution has been discussed in #530 as a …
=> Issue 530 silence sentry logs

src/org/opendatakit/briefcase/util/PullFromServerException.java, src/org/opendatakit/briefcase/util/TransferFromServer.java
Closes #558
This PR doesn't change behavior.
This PR introduces a technical change to add information to an error log in order to try to know if there's a bug behind it or not.
It's not clear how to reproduce the error that would let us know if the change works, but it's a really straightforward change and it doesn't affect to any other part of Briefcase. It should be safe to merge. 
This PR follows the good practice to not losing the causing exception when wrapping it in a domain exception.
Nope.
Nope.
=> Issue 558 Attach causing exception to domain exception

src/org/opendatakit/briefcase/ui/settings/SettingsPanelForm.java
This PR changes the locking behavior of the reload forms button, which stayed enabled all the time, even when there was no storage dir set.
The new behavior is:
- Disable it by default
- Enable it when the storage directory is set
- Disable it again when the storage directory gets cleared
- Verify it is disabled on first launch after clearing prefs.
- Verify it is enabled after setting the storage dir
- Verify it gets disabled when clearing the storage dir
It's the most straighforward change I could come up with to support the behavior we want.
Nope.
Nope.
=> Fix behavior of reload forms button

src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java
Closes #586 
I have checked the confirmation message on Export tab. Once the user clicks on Overwrite Existing FIles checkbox, the confirmation message is displayed as follows:
It is a simple change of confirmation message.
No.
=> Modified Export overwriting files confirmation message. Fix #586

.circleci/config.yml
Closes #596 
Force CircleCI to use the latest Java8 image
- Instead of using the lastest "latest" version which at the time of this commit is 10.0.2 (Oracle)
- This is to avoid a failure while testing due to JaCoCo incompatibilities
Tested that now the project builds in CircleCI
This is a straightforward change to avoid depending on a CircleCI env that we can't control.
Nope
Nope
=> Issue 596 Specify the correct Java image for CircleCI builds

.circleci/config.yml, src/org/opendatakit/briefcase/export/CsvSubmissionMappers.java, src/org/opendatakit/briefcase/export/ExportConfiguration.java, src/org/opendatakit/briefcase/export/ExportMediaOverrideOption.java, src/org/opendatakit/briefcase/operations/Export.java, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanel.java, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.form, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelMode.java, test/java/org/opendatakit/briefcase/export/ExportConfigurationTest.java, test/java/org/opendatakit/briefcase/export/ExportToCsvScenario.java
Closes #580 
This PR changes the behavior of the custom conf dialogs. Now, the user can choose to inherit whichever setting for export media is set in the default configuration panel or override it to enable or disable it.
These changes imitate what we did to solve the same situation with the "pull before export" setting.
- Wrote new tests for the resolution of effective export media conf param.
- Run cycles of setting some scenario, relaunching Briefcase and verifying that the scenario was correctly saved & restored:
| Default | Custom | Resolved to |
|---|---|---|
|ON|INHERIT|ON|
|ON|ON|ON|
|ON|OFF|OFF|
|OFF|INHERIT|OFF|
|OFF|ON|ON|
|OFF|OFF|OFF|
- Verified with the Birds form that media files where exported according to each scenario
This imitates previous solution to the same problem. …
=> Issue 580 fix export custom conf export media

src/org/opendatakit/briefcase/reused/RemoteServer.java, src/org/opendatakit/briefcase/reused/UncheckedFiles.java, test/java/org/opendatakit/briefcase/export/CsvFieldMappersTest.java, test/java/org/opendatakit/briefcase/export/ExportToCsvScenario.java
Closes #593 
This PR explicitly uses UTF-8 for all NIO2 file writing operations and some `InputStreamReader` that was using the default charset.
This reportedly solves a [forum user's issues](https://forum.opendatakit.org/t/csv-file-lao-characters-not-showing-after-export-from-odk-briefcase/14075/17) with Lao characters being incorrectly encoded while exporting forms in Briefcase.
Run the automated tests.
This changes code that depended on the JDK's default charsets while writing to files with an explicit use of UTF-8 in write operations, which will have a consistent behavior across different platforms and environments.
Nope.
Nope.
=> Force utf8 encoding

test/java/org/opendatakit/briefcase/export/CsvFieldMappersTest.java
Closes #594
This PR adds test cases for the decimal number field mapper
- It includes a case that uses a locale that would encode decimals using a comma for the decimals separator
Some insights after exploring the code for decimal number encoding issues:
- Fields with `DataType.DECIMAL` don't have a specific `CsvFieldMapper` instance, which means that whatever value comes in the XML submission, it comes out untouched
- The `CsvSubmissionMapper` takes care about escaping values before writing them to the CSV file. If the output of a `CsvFieldMapper` includes a comma, a `CsvSubmissionMapper` will wrap it with double quotes, making it safe.
- There are tests for this.
All looks like we're safe at the moment. The new test cases aren't even strictly necessary, but they will prevent regression …
=> Issue 594 Explore, document and add test cases of decimal numbers in the export output

test/java/org/opendatakit/briefcase/reused/http/CommonsHttpTest.java
This PR fixes a test of the real http adapter. We used to get the main ODK docs page and assert that the text "Welcome to Open Data Kit", but they just changed that :P
Now we narrow the expected text to just "Open Data Kit".
Run the automated test
We could spin a lightweight http server from the test to ensure this problem never happens again, but that's too complex right, although we could eventually consider doing it.
Nope. It's just a fix on an assertion of a test to avoid false negatives.
Nope
=> Make the test less brittle by narrowing the assertion

build.gradle, src/org/opendatakit/briefcase/export/Model.java, test/java/org/opendatakit/briefcase/export/CsvSubmissionMappersEncodeMainValueTest.java
Closes #617
This PR doesn't change Briefcase's behavior
This PR updates the JR lib version and adapts to a breaking change that was introduced:
- `DataType.CHOICE_LIST` has been replaced by `DataType.MULTIPLE_ITEMS`
Run the automated tests
We could always _not_ update the JR version but the longer we wait, the bigger the adaptation changes will be. Better to do have smaller changesets.
None.
No.
=> Issue 617 update jr to 2.11.2 and adapt

src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java
Closes #608 
This PR forces the overwrite confirmation dialog to appear using a dialog configured to be always on top as its parent component. This ensures that it stays on top of any other dialogs, even in a Mac computer.
- Run in Linux and verified that it still works OK
- Run in Mac and verified that now it shows correctly on top
Although hacking Swing UI components is always a gamble, this change seems reasonably simple and safe.
None.
Nope.
=> Issue 608 Overwrite dialog displays behind Default export Conf instead of in front of on MacOS

src/org/opendatakit/briefcase/operations/Export.java, src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java, src/org/opendatakit/briefcase/transfer/NewTransferAction.java, src/org/opendatakit/briefcase/ui/BriefcaseCLI.java, src/org/opendatakit/briefcase/ui/export/ExportPanel.java, src/org/opendatakit/briefcase/ui/pull/PullPanel.java, src/org/opendatakit/briefcase/ui/reused/source/Source.java, src/org/opendatakit/briefcase/util/ServerFetcher.java, src/org/opendatakit/briefcase/util/TransferAction.java, src/org/opendatakit/briefcase/util/TransferFromServer.java
Closes #613
This PR adds a new CLI param to enable requesting incomplete submissions when pulling from Aggregate.
It would be easier to test this PR with an Aggregate server that supports the new parameter. (Will post here the PR/version when it's available)
Used the CLI pull from aggregate op with the new flag and verified on the logs that the requested URL included the `&includeIncomplete=true` part in its query string (INFO log level has to be enabled in the logback conf settings).
Although the code is quite coupled and I've had to pass a new arg around changing many classes, this is the narrowest change I could come up with.
Aggregate doesn't complain about the new arg, even if it doesn't support it (maybe it's an older version without support for this). I can't say the same about …
=> Issue 613 cli param to pull incomplete subs

src/org/opendatakit/briefcase/ui/reused/source/SelectSourceForm.java, src/org/opendatakit/briefcase/ui/reused/source/ShowSourceForm.form, src/org/opendatakit/briefcase/ui/reused/source/ShowSourceForm.java, src/org/opendatakit/briefcase/ui/reused/source/Source.java, src/org/opendatakit/briefcase/ui/reused/source/SourcePanel.java
This closes issue #612 
A form was both added and deleted from the Aggregate server. After each step the reload button was pressed and the 'pull' view reflected the new state of the Aggregate server.
This is the first implementation and is open to discussion.
There are no automated tests written to cover this functionality. I'm open to hear about how this feature can be automatically tested.
I'm not sure if this feature mandates an update to the documentation.
=> Issue #612 Reload button for Aggregate option under pull tab

src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java
Disable temporarily the optional CLI `-ii` param while the a new Aggregate version that supports downloading incomplete submissions is released
=> Disable temporarily the optional CLI -ii param

src/org/opendatakit/briefcase/export/ExportConfiguration.java, src/org/opendatakit/briefcase/export/ExportToCsv.java, src/org/opendatakit/briefcase/export/SubmissionParser.java, src/org/opendatakit/briefcase/reused/UncheckedFiles.java
Addresses #611
This PR doesn't change Briefcase's behavior.
This PR changes the export process to copy failed submissions to a new error directory inside the export directory. This will let users attach the specific submissions that are failing when reporting issues with Briefcase.
To test this PR, use this storage dir which includes two forms with failing submissions.
[storage_dir.zip](https://github.com/opendatakit/briefcase/files/2331987/storage_dir.zip)
- Pull a form with submissions
- Tamper with a submission by introducing XML syntax errors
- Export the form
- Verify that the invalid form is inside an `errors of NAME OF THE FORM` directory inside the choosen export directory. The submission should have a `failed_submission_1.xml` filename. The number should follow a sequence if …
=> Issue 611 export save failed submissions

src/org/opendatakit/briefcase/export/CsvSubmissionMappers.java, src/org/opendatakit/briefcase/export/ExportToCsv.java, src/org/opendatakit/briefcase/export/FormDefinition.java, src/org/opendatakit/briefcase/export/Submission.java, src/org/opendatakit/briefcase/export/SubmissionExportErrorCallback.java, src/org/opendatakit/briefcase/export/SubmissionParser.java, src/org/opendatakit/briefcase/ui/export/ExportPanel.java, test/java/org/opendatakit/briefcase/export/SubmissionTest.java
Addresses #625
This PR fixes a regression that produces an error when some of the exported submissions have no instance ID.
Now, no error will be shown and the invalid submissions will be excluded and copied to the error output directory.
The definition of a valid submission is:
- The form it belongs to doesn't define repeat groups
OR 
- it has an instance id
This means that for a submission with repeat groups to be valid, it needs to have an instance id. This makes sense because, otherwise, it wouldn't be possible to link the lines from the output repeat CSV file to their corresponding lines on the on the main CSV output files.
When a form doesn't define repeat groups, though, it's perfectly reasonable to not have instance ids, and the output CSV file will have blank values on that …
=> Issue 625 export subs without instance id

src/org/opendatakit/briefcase/export/Csv.java, src/org/opendatakit/briefcase/export/ExportConfiguration.java, src/org/opendatakit/briefcase/export/ExportToCsv.java, src/org/opendatakit/briefcase/model/FormStatus.java, src/org/opendatakit/briefcase/ui/export/ExportPanel.java, src/org/opendatakit/briefcase/ui/export/ExportPanelForm.form, src/org/opendatakit/briefcase/ui/export/ExportPanelForm.java, src/org/opendatakit/briefcase/util/ErrorOr.java, test/java/org/opendatakit/briefcase/export/ExportConfigurationTest.java, test/java/org/opendatakit/briefcase/export/ExportToCsvEncryptedMediaTest.java, test/java/org/opendatakit/briefcase/export/ExportToCsvEncryptionTest.java, test/java/org/opendatakit/briefcase/ui/export/ExportPanelTest.java, test/java/org/opendatakit/briefcase/ui/export/ExportPanelUnitTest.java, test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java
Closes #628
This PR changes the behavior of the export button on the UI.
Now, the button will be always enabled & clickable by the user, except while an export process is on the way.
When the button is clicked we check that:
- at least one form has been selected
- all selected forms have been configured with an export directory
- Either by the default configuration
- Or by custom individual configurations
- all encrypted forms have been configured with a PEM file
- Either by the default configuration
- Or by custom individual configurations
If any of these checks fail, we show a dialog informing the user about this and calling for action.
If none of these checks fail, the export process starts.
- Tested manually on the UI each check in isolation and combined with unencrypted forms and …
=> Issue 628 change export button behavior

src/org/opendatakit/briefcase/export/ExportConfiguration.java, src/org/opendatakit/briefcase/ui/pull/FormInstaller.java, src/org/opendatakit/briefcase/util/FileSystemUtils.java
Closes #230
This ensures that file and directories created by Briefcase don't have illegal characters:
- Export errors output directory
- A form's directory in the storage dir when it's installed individually
This PR also flags legacy places that should be reviewed when refactored.
Since the `stripIllegalChars` method has been already tested, no special checks have been made, other than compiling and running the automated test.
We could refactor the legacy places but it doesn't feel worth it:
- It feels risky changing a piece of code that nobody's complained for a long time ago
- We will probably have to change it when we implement planned features like the central Database, or when we refactor the low-level form pulling code to improve the concurrency model
My gut feeling is that …
=> Issue 230 ensure safe dir and file names

src/org/opendatakit/briefcase/export/ExportForms.java
Closes #603 
I tried to reproduce the issue following the steps mentioned in the issue description. I can't see that issue anymore.
Manual testing instructions:
- Ensure that the remember passwords setting is enabled
- Pull a form from an Aggregate server using the anon account (enter no credentials)
- Close Briefcase
- Open Briefcase
- Go to the export tab
- Open the custom conf dialog for the form you've pulled on step 2
- Verify that now you can override the "Pull before export" conf param
On master, you wouldn't be able to do so.
For anonymous account, we check if username and password is null or empty.
No.
No.
=> 603 pull sources

res/logback.xml.example-release
This PR doesn't change Briefcase's behavior.
This PR removes the Sentry appender from the Logback production example conf file, since won't be relying on that to get error reports to Sentry after #564.
There are no code changes. Nothing to verify :)
This is just something I forgot to do in #564. It's surfaced after doing a release and realizing that the file still had the appender.
Users won't notice a thing.
Nope.
=> Remove the sentry appender from the prod example conf file

src/org/opendatakit/briefcase/export/ExportConfiguration.java, test/java/org/opendatakit/briefcase/export/ExportConfigurationTest.java
Closes #657
Add and run a new automated test that ensures the filename has the `csv` extension.
Manually run the JAR to verify it works.
This PR fixes a regression introduced in v1.11
No.
=> Issue 657 Fix adding csv extension when given filename doesn't include it

src/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialog.java, src/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialogForm.java
Closes #651 
We set the cursor to waiting after click the connection button but forget to set it back when an error happens, it's a small improvement but makes the user more comfortable when backing to the configuration dialog. 
It's the best solution, and it's really simple.
=> Issue 651 fixed the busy cursor after error happens

src/org/opendatakit/briefcase/export/Csv.java, src/org/opendatakit/briefcase/export/CsvFieldMapper.java, src/org/opendatakit/briefcase/export/CsvFieldMappers.java, src/org/opendatakit/briefcase/export/CsvSubmissionMappers.java, src/org/opendatakit/briefcase/export/ExportConfiguration.java, src/org/opendatakit/briefcase/export/ExportToCsv.java, src/org/opendatakit/briefcase/export/Model.java, src/org/opendatakit/briefcase/export/SplitSelectMultiples.java, src/org/opendatakit/briefcase/reused/UncheckedFiles.java, test/java/org/opendatakit/briefcase/export/CsvFieldMappersTest.java, test/java/org/opendatakit/briefcase/export/CsvSubmissionMappersEncodeMainValueTest.java, test/java/org/opendatakit/briefcase/export/CsvSubmissionMappersEncodeValueTest.java, test/java/org/opendatakit/briefcase/export/ExportConfigurationTest.java, test/java/org/opendatakit/briefcase/export/ModelTest.java, test/java/org/opendatakit/briefcase/export/Scenario.java, test/java/org/opendatakit/briefcase/matchers/PathMatchers.java
Closes #637
It appears that GitHub has reordered some commits, which could be a little confusing for the reviewer of this PR. Sorry about that! ¯\\\_(ツ)\_/¯
- Run the automated tests
- Manually exported [Audit 1](https://github.com/opendatakit/briefcase/files/2370724/audit-1.txt), and [Audit 2](https://github.com/opendatakit/briefcase/files/2370723/audit-2.txt) forms with some submissions.
This is the narrowest change I could think of. It ensures that previous behavior doesn't change by adding a new mapper instead of changing the current binary mapper.
There are some ways we could address a performance decrease (see last section):
- we could post-process of the submissions and writing once in the output audit file
- we could change the side-effect of the new field mapper (writing to a …
=> Issue 637 merge audit files

src/org/opendatakit/briefcase/export/Model.java, test/java/org/opendatakit/briefcase/export/CsvTest.java, test/java/org/opendatakit/briefcase/export/ExportConfigurationTest.java, test/java/org/opendatakit/briefcase/export/ModelBuilder.java, test/java/org/opendatakit/briefcase/export/ModelTest.java, test/java/org/opendatakit/briefcase/export/XmlElementTest.java
Closes #656
Run automated tests that verify that a multiple select with a `search()` appearance will give an empty list of fields.
This is the narrowest solution I can think of. Most of the code in this PR is for testing.
This will produce a more coherent behavior when using the split multiple selects option when exporting forms.
https://github.com/opendatakit/docs/issues/879
=> Issue 656 split selects with search appearance

src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java
This PR re-enabled the -ii flag to include incomplete submissions when pulling forms from Aggregate.
This PR should be merged after https://github.com/opendatakit/aggregate/pull/306 has been released.
Manual QA testing by @kkrawczyk123 
https://github.com/opendatakit/docs/issues/843
=> Re-enable the CLI flag to include incomplete submissions when pulling

src/org/opendatakit/briefcase/export/CsvFieldMappers.java, test/java/org/opendatakit/briefcase/export/CsvFieldMappersTest.java
Closes #665
Added automated tests that cover the changes
Also tested manually using the UI and this form: [უნივერსიტეტის გამოკითხვა.zip](https://github.com/opendatakit/briefcase/files/2501380/default.zip)
This PR uses the current binary field mapper as a base for the individual audit file mapper and adds the smallest possible changes to deal with the filename.
Users won't have individual audit files with sequence numbers in the output `media` folders. Now, all audit files include the instance ID, which prevents name collisions and makes the files more useful for users, since it's easier to link the files to their corresponding rows in the output CSV files.
No, but I could be convinced to cover the audit exports on the docs.
=> Issue 665 use instance id for sequencing audit files

docs/export-format.md, src/org/opendatakit/briefcase/export/Csv.java, src/org/opendatakit/briefcase/export/ExportConfiguration.java, src/org/opendatakit/briefcase/export/ExportToCsv.java, src/org/opendatakit/briefcase/export/Model.java, test/java/org/opendatakit/briefcase/export/CsvTest.java, test/java/org/opendatakit/briefcase/export/ExportConfigurationTest.java, test/java/org/opendatakit/briefcase/export/ModelBuilder.java, test/java/org/opendatakit/briefcase/export/ModelTest.java, test/java/org/opendatakit/briefcase/export/XmlElementTest.java
Closes #663 
Add automated tests that cover the changes
These are narrow changes to support the change on filenames and the sequencing of files for deduplication.
This PR changes the filenames of output CSV files of repeat groups. Now, we use unqualified names and when more than one repeat group share the same name, we add a sequence number to the filenames for deduplication.
Sequence numbers start on 1 and assignation happens following a depth-first order.
I've tried this PR with two forms:
- [dupe-sibling-repeats.zip](https://github.com/opendatakit/briefcase/files/2556958/dupe-sibling-repeats.zip)
```
group1
dupe-repeat
group2
dupe-repeat
```
- [dupe-nested-repeats.zip](https://github.com/opendatakit/briefcase/files/2556960/dupe-nested-repeats.zip)
```
outer-group
dupe-repeat …
```
=> Issue 663 unqualified group names csv export

src/org/opendatakit/briefcase/export/Csv.java, src/org/opendatakit/briefcase/export/CsvSubmissionMappers.java, src/org/opendatakit/briefcase/export/ExportConfiguration.java, src/org/opendatakit/briefcase/export/Model.java, src/org/opendatakit/briefcase/operations/Export.java, src/org/opendatakit/briefcase/ui/BriefcaseCLI.java, test/java/org/opendatakit/briefcase/export/CsvSubmissionMappersHeadersTest.java, test/java/org/opendatakit/briefcase/export/ExportConfigurationTest.java
Closes #671
This PR is built on top #669 and the first commit is https://github.com/opendatakit/briefcase/pull/674/commits/d0aef21a97450287396ea9a41ebb0c8e1ff36cea
Try it with this Briefcase JAR: 
[briefcase-674-remove-group-names.jar.zip](https://github.com/opendatakit/briefcase/files/2561259/briefcase-674-remove-group-names.jar.zip)
Added new automated tests
Run the export of All Widgets form
Also exported [field-in-group.zip](https://github.com/opendatakit/briefcase/files/2557123/field-in-group.zip), which that has a field in a non-repeat group.
- Without `-rgn` builds this header: `SubmissionDate,meta-instanceID,group-some-field,KEY`
- With `-rgn` builds this header: `SubmissionDate,instanceID,some-field,KEY`
No other approaches considered. The code that generates the headers is very …
=> Issue 671 export param to remove group names

src/org/opendatakit/briefcase/export/ExportConfiguration.java, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.form, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java, src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelMode.java
Closes #687
Tested manually with [choice-lists.zip](https://github.com/opendatakit/briefcase/files/2648642/choice-lists.zip), which has a field in a group.
Tested all combinations of default conf and overridden conf.
This PR imitates what's being done with all the other overridable boolean export conf params.
Users should be able to enable removing the group names from the CSV header lines thanks to a new checkbox (default conf panel) and overridable boolean (custom conf panel)
Yes:
=> Issue 687 export ui conf param remove group names

src/org/opendatakit/briefcase/ui/reused/UI.java, src/org/opendatakit/briefcase/ui/reused/source/ShowSourceForm.java, src/org/opendatakit/briefcase/ui/reused/source/Source.java
Closes #688
Tested manually all possible sources on pull and push tabs.
I researched different options to make stuff clickable in Swing and I went for this one because it was the simplest way to get it done. Other alternatives involve more complex listeners and/or using custom-styled buttons instead of labels.
This PR makes clickable the URLs to the Aggregate sources/targets configured on the Pull and Push tabs. They will open the default browser.
Nope.
=> Issue 688 Make pull and push urls clickable in the UI

src/org/opendatakit/briefcase/export/CsvSubmissionMappers.java, src/org/opendatakit/briefcase/export/Model.java, test/java/org/opendatakit/briefcase/export/CsvSubmissionMappersHeadersTest.java, test/java/org/opendatakit/briefcase/export/ModelBuilder.java, test/resources/org/opendatakit/briefcase/export/choice-lists-submission.xml, test/resources/org/opendatakit/briefcase/export/choice-lists.csv.expected, test/resources/org/opendatakit/briefcase/export/choice-lists.xml
Closes #689
Try it: [briefcase-pr690.zip](https://github.com/opendatakit/briefcase/files/2648446/briefcase-pr690.zip)
Added new integration and unit tests
No other approaches considered. This solution makes the code around header generation more consistent with pre-existing code (geopoints)
Users should expect that splitting select multiples inside and outside non-repeat groups to behave similarly.
Nope.
=> Issue 689 split select multiples in groups

build.gradle, src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java
Closes #700, and #699
The project compiles and Briefcase runs.
I've tested that the issue with #699 gets solved by using this form [guidance.xml.zip](https://github.com/opendatakit/briefcase/files/2840104/guidance.xml.zip)
which fails in master (the form is from https://github.com/XLSForm/pyxform/issues/225 which was linked in #699)
It's a very small change: version bump, sync serializable class list (copied from JR)
N/A
No.
=> Issue 700 Update JavaRosa

src/org/opendatakit/briefcase/util/ServerFetcher.java, test/java/org/opendatakit/briefcase/util/ServerFetcherTest.java
Closes #695
**On Onadata**
- Create an account at https://odk.ona.io/
- Upload the form [pizza_questionnaire.xlsx](https://github.com/opendatakit/briefcase/files/2755542/pizza_questionnaire.xlsx)
**On Briefcase**
- Configure the aggregate server with `https://odk.ona.io/{username}` (and your Ona credentials)
- Pull form
This is a small change to check that whatever value coming on the manifestUrl is an url. This will prevent trying to get manifests when the server reports a `<manifest/>` tag when downloading a blank form (which is the default behavior in Ona).
N/A
No
=> Issue 695 Support empty manifest URLs when pulling forms

src/org/opendatakit/briefcase/model/BriefcasePreferences.java, src/org/opendatakit/briefcase/operations/Export.java, src/org/opendatakit/briefcase/operations/ImportFromODK.java, src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java, src/org/opendatakit/briefcase/operations/PushFormToAggregate.java, src/org/opendatakit/briefcase/pull/FormInstaller.java, src/org/opendatakit/briefcase/pull/PullEvent.java, src/org/opendatakit/briefcase/push/PushEvent.java, src/org/opendatakit/briefcase/transfer/NewTransferAction.java, src/org/opendatakit/briefcase/transfer/TransferForms.java, src/org/opendatakit/briefcase/ui/BriefcaseCLI.java, src/org/opendatakit/briefcase/ui/export/ExportPanel.java, src/org/opendatakit/briefcase/ui/pull/PullPanel.java, src/org/opendatakit/briefcase/ui/reused/source/Source.java, src/org/opendatakit/briefcase/ui/settings/SettingsPanel.java, src/org/opendatakit/briefcase/ui/settings/SettingsPanelForm.form, src/org/opendatakit/briefcase/ui/settings/SettingsPanelForm.java, src/org/opendatakit/briefcase/util/PullFromODKException.java, src/org/opendatakit/briefcase/util/PullFromServerException.java, src/org/opendatakit/briefcase/util/PushFromServerException.java, src/org/opendatakit/briefcase/util/ServerFetcher.java, src/org/opendatakit/briefcase/util/ServerUploader.java, src/org/opendatakit/briefcase/util/TransferAction.java, src/org/opendatakit/briefcase/util/TransferFromODK.java, src/org/opendatakit/briefcase/util/TransferFromServer.java, src/org/opendatakit/briefcase/util/TransferToServer.java
Closes #681
Tested manually on Linux(Ubuntu) using an Aggregate v2.0 local server
This PR tries to store a byproduct of the pre-existing pull process that was being discarded (the cursor uses during interaction with the Aggregate API). 
There are new user facing options:
- There's a new global setting to enable resuming pulls in the Settings tab
- There's a new button in the settings tab that clears any saved resume cursors
- There's a new CLI flag `-rlp` or `--resume_last_pull` to enable the feature from the command line
Yes, https://github.com/opendatakit/docs/issues/967
=> Issue 681 resume last pull

src/org/opendatakit/briefcase/util/ServerFetcher.java
Closes #709 
Reproduce the error with the [Birds](https://github.com/opendatakit/sample-forms) form, fix the bug and check that now it pulls the attachments.
This fixes a silly mistake in an `if` condition.
N/A
Nope.
=> Issue 709 Fix downloading form media attachments

src/org/opendatakit/briefcase/operations/ImportFromODK.java, src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java, src/org/opendatakit/briefcase/operations/PushFormToAggregate.java
Closes #711 
**Context**
https://github.com/opendatakit/briefcase/pull/698/commits/7eccb568b4cba72f1da5ca3ecc42fe9b3841117f introduced a change that migrated the transfer(pull&push) code to use `TransferForms` instead of a generic `List<FormStatus>`. `TransferForms` has the notion of "selected forms" and downstream pull and push operation code does `forms.getSelectedForms()`.
The CLI wasn't adapted to this fact by accident, which introduced the bug that this PR solves.
Run the pull from collect command to ensure that it works as expected:
- no form-id > pull all forms present
- form-id > pull just that form
This PR makes changes to have the CLI doing the same as the UI (select the forms)
Users should be able to pull and push forms again using the CLI
Nope.
=> Ensure that CLI ops select the forms they need to transfer

src/org/opendatakit/briefcase/operations/Export.java
Closes #714
Run the export command, verify that Briefcase CLI creates the export dir.
Super narrow change to ensure that the export dir exists.
Users will be able to launch export CLI operations without having to previuosly create the export dir.
No.
=> Issue 714 fix selecting forms in cli ops

src/org/opendatakit/briefcase/export/FormDefinition.java, src/org/opendatakit/briefcase/export/Model.java, test/java/org/opendatakit/briefcase/export/ExportToCsvExplodeChoiceListWithPredicateTest.java, test/resources/org/opendatakit/briefcase/export/choice-lists-predicate-submission.xml, test/resources/org/opendatakit/briefcase/export/choice-lists-predicate.csv.expected, test/resources/org/opendatakit/briefcase/export/choice-lists-predicate.xml
Closes #723
Add automated tests covering the new scenario
Run Briefcase manually to export this form: [choice-lists-predicate.txt](https://github.com/opendatakit/briefcase/files/2975020/choice-lists-predicate.txt)
This is a narrow fix to support the scenario described in #721
Users now can expect to export forms and split any select multiple control if their itemsets use internal secondary instances, whether they have predicates or not.
Nope.
=> Issue 723 split select multiple with predicates on internal secondary instances

src/org/opendatakit/briefcase/transfer/TransferForms.java, test/java/org/opendatakit/briefcase/transfer/TransferFormsTest.java
Closes #725
Added automated tests
Avoid immutable lists to prevent UnsupportedOperationException
- The clear() and merge() methods will throw the exception on immutable subtypes
- By using the ArrayList<>() constructor instead of Collections.emptyList() or Arrays.asList() we prevent throwing the exception
Users should expect no errors from this source when working with the pull and push tabs
No.
=> Issue 725 Avoid UnsupportedOperationException in TransferForms

src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java, src/org/opendatakit/briefcase/ui/BriefcaseCLI.java
Closes #721 
I checked the forms displayed in UI and compared with what was downloaded.
Made the form_id argument optional.Similar to ```ImportFromODK```
If you run the command ```java -jar ODK-Briefcase-v1.14.0.jar -plla -sd /Users/yanokwa/Desktop -u admin -p admin -url https://example.com``` it should download all the forms from aggregate server. If you specify ```form_id``` argument then it just downloads the specified form.
=> 721 pull all forms

src/org/opendatakit/briefcase/operations/Export.java, src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java, src/org/opendatakit/briefcase/transfer/NewTransferAction.java, src/org/opendatakit/briefcase/ui/BriefcaseCLI.java, src/org/opendatakit/briefcase/ui/export/ExportPanel.java, src/org/opendatakit/briefcase/ui/pull/PullPanel.java, src/org/opendatakit/briefcase/ui/reused/source/Source.java, src/org/opendatakit/briefcase/util/ServerFetcher.java, src/org/opendatakit/briefcase/util/TransferAction.java, src/org/opendatakit/briefcase/util/TransferFromServer.java
Closes #729 
Used a form in the sandbox with submissions to test this feature:
- Pull the form with `-sfd` and verify that the expected amount of submissions are pulled.
- Send some submissions and pull the form using the same `-sfd` date. Verify that only the new submissions get pulled.
This PR is a narrow change on top of the existing `-sfl` feature.
This PR should not have other effects other than the new added feature described in #729.
"start from date" will update the last cursor so that the next pull with "start from last" continues pulling from the next submission.
The CLI will ignore `-sfd` when combined with `-sfl`.
Yes! https://github.com/opendatakit/docs/issues/993
=> Issue 729 cli pull start from date

src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/ShowSourceOrTargetForm.form, src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/ShowSourceOrTargetForm.java, src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/Aggregate.java, src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/Central.java, src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/target/Aggregate.java, src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/target/Central.java
Closes #749
Manually tested (Ubuntu) that Aggregate and Central servers show the new labels and rows accordingly.
Aggregate servers should say:
- (Pulling from|Pushing to): Aggregate server
- URL: http://foo.bar
Central servers should say:
- (Pulling from|Pushing to): Central server
- URL: http://foo.bar
- Project ID: 42
This is the narrowest solution I could come up with that doesn't require changing the Swing layout, which is always good.
The change is so small, and affects only to the presentation layer, that I don't think there's any regression risks.
Maybe Windows and Mac struggle with <br/> tags in html labels?
Nope.
=> Issue #749 Improve layout of the show source panel to better acommodate info

src/org/opendatakit/briefcase/model/RemoteFormDefinition.java, src/org/opendatakit/briefcase/pull/aggregate/AggregateCursor.java, src/org/opendatakit/briefcase/pull/aggregate/Cursor.java, src/org/opendatakit/briefcase/pull/aggregate/EmptyCursor.java, src/org/opendatakit/briefcase/pull/aggregate/InstanceIdBatchGetter.java, src/org/opendatakit/briefcase/pull/aggregate/OnaCursor.java, src/org/opendatakit/briefcase/pull/aggregate/PullFromAggregate.java, src/org/opendatakit/briefcase/reused/http/CommonsHttp.java, src/org/opendatakit/briefcase/reused/http/RequestBuilder.java, src/org/opendatakit/briefcase/reused/transfer/AggregateServer.java, src/org/opendatakit/briefcase/reused/transfer/CentralServer.java, test/java/org/opendatakit/briefcase/pull/aggregate/OpenRosaCursorTest.java, test/java/org/opendatakit/briefcase/reused/http/RequestBuilderTest.java, test/java/org/opendatakit/briefcase/reused/transfer/AggregateServerTest.java, test/java/org/opendatakit/briefcase/reused/transfer/TransferTestHelpers.java
This PR solves issues when dealing with Ona servers:
- Can't connect to list forms in the pull tab
- Can't use the "start from last" feature when pulling forms
- Can't use the "pull before export" feature when exporting forms.
I've tested this manually using my Ona account at https://odk.ona.io/ggalmazor
- Pull forms under various "start from last" scenarios: first time pull, second time pull, send new submissions and pull again, etc.
- Export forms with the "pull before export" option:
- Single form
- Multiple form, from Ona and Aggregate servers
Subtyping Cursor felt like the simplest way to go. The alternative would have been to revert the changes to Cursor that made it parse its value, but that would have an impact on how we deal with the "start from date" feature.
The changes to …
=> Fix non Aggregate compatibility

src/org/opendatakit/briefcase/operations/Common.java, src/org/opendatakit/briefcase/operations/Export.java, src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java, src/org/opendatakit/briefcase/operations/PushFormToAggregate.java, src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java, src/org/opendatakit/briefcase/ui/settings/SettingsPanelForm.form, src/org/opendatakit/briefcase/ui/settings/SettingsPanelForm.java
Closes #751
Review language about max http connections conf setting
- Outside CommonsHttp, we use "max http connections"
- Inside CommonsHttp, we use "max connections"
- For user-facing texts, we use "maximum simultaneous HTTP connections"
Run the CLI help and the UI to verify that user-facing texts are alright.
The rest of the changes can be verified by building the project since they're only safe name change refactors.
This is a small change to review code and text language use. 
We considered using "max connections" and "max HTTP connections", but ultimately decided that "max simultaneous HTTP connections" was the shortest form that gave all necessary context.
Nope.
Nope.
=> Issue #751 Change max HTTP conns language

src/org/opendatakit/briefcase/reused/http/RequestBuilder.java
Closes #761
Manually tested on a Windows 10 machine using the form attached to the issue
Manually tested on Linux to ensure that it still worked as expected on another system.
This is a narrow fix and I didn't consider any other approach.
It feels like it's a safe change with no risk of affecting in an unpredictable manner.
Nope.
=> Issue #761 Encoding issues when pulling submissions with Arabic characters in Windows

config/checkstyle/checkstyle.xml, src/org/opendatakit/briefcase/export/CsvFieldMappers.java, src/org/opendatakit/briefcase/reused/Iso8601Helpers.java, test/java/org/opendatakit/briefcase/reused/Iso8601HelpersTest.java
Closes #759
This PR has a stowaway change: removing the `WhitespaceAround` rule from the checkstyle config file:
- This rule is super noisy because every time that someone makes a change to a UI form using IntelliJ's GUI Designer, it generates code in their companion classes that offends the rule at least once. If the form has customized fonts it's even worse because there are multiple offending lines that you need to search and change *every time*.
- This rule can be annoying when dealing with no-op functions as `() -> {}`, forcing to write them with an empty space between the brackets, or simple enums such as `enum Type {A, B}`, forcing you to sandwich the enum values between whitespaces.
- I don't think this particular rule helps us to write particularly easier to read code, so I've …
=> Issue 759 fix parsing times with unsupported offsets

src/org/opendatakit/briefcase/pull/aggregate/Cursor.java, src/org/opendatakit/briefcase/pull/aggregate/OpaqueCursor.java, test/java/org/opendatakit/briefcase/pull/aggregate/AggregateCursorTest.java, test/java/org/opendatakit/briefcase/pull/aggregate/CursorHelpers.java, test/java/org/opendatakit/briefcase/pull/aggregate/CursorTest.java, test/java/org/opendatakit/briefcase/pull/aggregate/OpenRosaCursorTest.java
Closes #768 
Since we can't test every aggregate compatible server, I've added automated tests covering the fallback option.
This is what should have been shipped in v1.16 in the first place. An opaque cursor implementation as a fallback for non-aggregate server is the most reasonable way to maintain compatibility with non aggregate servers.
Code with the solution was cherry picked from https://github.com/cims-bioko/briefcase/commit/91ca88ac274a3c8e52222127c69c9119c8a64d96 (thanks, @batkinson!)
Users using non-aggregate servers should be able to pull forms from their servers after this PR gets merged.
Nope.
=> Provide fallback cursor implementation

src/org/opendatakit/briefcase/reused/http/CommonsHttp.java
Closes #777
Manually test against bleeding edge Central server at antinod.es
Central (latest) will reject requests arriving with auth tokens and session cookies. Since we don't really need cookies for anything, this is a quick fix for this issue while we decide what to do about auth in Central
There's the risk of undocumented dependency on cookies by aggregate-compatible servers that we don't know about. If any of these servers rely upon cookies that were being sent, pull/push operations could fail due to this change. Testing in known servers (Ona, Kobo...) would be required to ensure we're breaking anything.
Nope.
=> Issue 777 Latest Central rejects multiple simultaneous auth methods

src/org/opendatakit/briefcase/reused/http/CommonsHttp.java, src/org/opendatakit/briefcase/reused/transfer/CentralAttachment.java
Closes #780
Manully verified using the UI and the instructions in the issue
Super narrow fix to ignore unknown/undeclared/unused props in incoming JSONs from Central
Pretty safe change behavior-wise.
Nope.
=> Issue #780 Parsing JSON Central responses fails when unexpected fields arrive

src/org/opendatakit/briefcase/export/FormDefinition.java, test/java/org/opendatakit/briefcase/export/ExportToCsvExplodeChoiceListWithRelativePredicateInRepeatTest.java, test/resources/org/opendatakit/briefcase/export/choice-lists-predicate-relative-repeat-group.csv.expected, test/resources/org/opendatakit/briefcase/export/choice-lists-predicate-relative-repeat-submission.xml, test/resources/org/opendatakit/briefcase/export/choice-lists-predicate-relative-repeat.csv.expected, test/resources/org/opendatakit/briefcase/export/choice-lists-predicate-relative-repeat.xml
Closes #789
- Added an automated regression test
- Manually exported the form attached in the issue and verified that it exports correctly when combined with the "split select multiples" feature.
Test this PR with [briefcase_pr_790.zip](https://github.com/opendatakit/briefcase/files/3515126/briefcase_pr_790.zip)
This is what feels safest from the three options described in #789 (maybe there are more options?). It's a straightforward change to prevent an NPE.
There's the risk of masking other sources of NPEs by the added try/catch block.
Nope.
=> Issue #789 Catch NPE while populating dynamic choices

src/org/opendatakit/briefcase/export/XmlElement.java, test/java/org/opendatakit/briefcase/export/ExportToCsvCaseSensitivityTest.java, test/resources/org/opendatakit/briefcase/export/simple-form-case-sensitivity-submission.xml, test/resources/org/opendatakit/briefcase/export/simple-form-case-sensitivity.csv.expected, test/resources/org/opendatakit/briefcase/export/simple-form-case-sensitivity.xml
Closes #791
Added automated regression test
Manually exported the form attached to the issue
Test this PR with [briefcase_pr_792.zip](https://github.com/opendatakit/briefcase/files/3515127/briefcase_pr_792.zip)
Super narrow fix to avoid confusing field mappers when two fields have the same name with case differences.
This shouldn't change any other behavior.
Nope.
=> Issue #791 Match case when finding xml element

src/org/opendatakit/briefcase/operations/ImportFromODK.java
Closes #735 
Manually tested it as shown in the screenshot:
This approach is similar to the one used in `PullFormFromAggregate` class.
https://github.com/opendatakit/briefcase/blob/master/src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java#L118
This change will inform the user in case the form id they entered is invalid. Before this, briefcase gave no error message and the user was under the impression that the desired pull operation was successful.
No
=> Fix #735 - Provide message when pulling non-existent form from odk dir using cmd

src/org/opendatakit/briefcase/ui/reused/UI.java
Closes #755 
Tested manually:
This is the best solution because it doesn't alter the backend logic of the system.
No risks. Slight UI misinformation is corrected.
No
=> Fix #755 - Set appropriate colour of view form details button.

src/org/opendatakit/briefcase/operations/PushFormToAggregate.java, src/org/opendatakit/briefcase/transfer/TransferForms.java
Closes #775
I added a bit of temporary logging code to see which forms were being pushed, and then manually ran a command like this:
```
$ java -jar build/libs/ODK-Briefcase-v1.16.0-1-g91f5f85f-dirty.jar --push_aggregate --aggregate_url https://sandbox.aggregate.opendatakit.org/ --odk_username foo --odk_password bar --storage_directory /tmp
```
All local forms were selected and pushed.
Straightforward change. This is substantially similar to the work done in #727.
The only user-facing change is that the form ID can be omitted, and this will be interpreted as selecting all forms.
I don't think so.
This seems to work for Aggregate, but the issue description mentions pushing to Central. Are parameters like `push_central` being added in 1.17? Is there anything else to be done right now?
=> 775: Push all forms to Aggregate if a form ID is not provided

src/org/opendatakit/briefcase/Launcher.java, src/org/opendatakit/briefcase/operations/Common.java, src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java, src/org/opendatakit/briefcase/operations/PullFormFromCentral.java, src/org/opendatakit/briefcase/operations/PushFormToAggregate.java, src/org/opendatakit/briefcase/operations/PushFormToCentral.java, src/org/opendatakit/briefcase/ui/BriefcaseCLI.java
Closes #763
This PR adds new pull from Central and push to Central CLI operations.
This PR deprecates `-url --aggregate_url` (see below)
Run both CLI operations using the `all-widgets` form and the Central sandbox at https://sandbox.central.opendatakit.org
This PR replicates the same things we already are doing for Aggregate server.
Instead of having shared args for things like the server's url and credentials, I considered having a separate set of args, but it felt bloated and not very reasonable overall.
To be able to share args for the server's url and credentials, I had to review the language on their shortcode, longcode, and descriptions, and I found an irreconcilable issue with the `-url --aggregate_url` argument. I had to either change the longcode to `--server_url` or deprecate it …
=> Issue 763 central cli ops

src/org/opendatakit/briefcase/export/ExportForms.java, src/org/opendatakit/briefcase/ui/export/ExportPanel.java, src/org/opendatakit/briefcase/ui/export/ExportPanelForm.java
Closes #732 
Manually tested with empty and filled forms list.
The approach used is similar to how things have been done in `PullPanel`.
This fixes a minor UI bug. No risks.
No
=> Fix #732 - Disable the select all button on Export tab if list is empty

src/org/opendatakit/briefcase/reused/transfer/CentralServer.java, src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/CentralServerDialog.java, src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/PullSource.java, src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/target/PushTarget.java
Closes #786 
Manually tested with correct and incorrect project IDs as shown below:
https://www.youtube.com/watch?v=Rd0Vuyg1PMg
I have tried to keep it as consistent with the current design as possible. 
This change will warn the user of an invalid project ID for the Central server at the time of setting up the connection. No risks to the users.
No
=> Fix #786 - Show error message when invalid project id is used for Central

src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java, src/org/opendatakit/briefcase/model/form/FormKey.java, test/java/org/opendatakit/briefcase/model/form/FormKeyTest.java, test/java/org/opendatakit/briefcase/ui/pull/FormInstallerTest.java, test/resources/form-with-special-chars.xml, test/resources/title-with-dashes-form.xml
Closes #799
Added an automated regression test
This is not an optimal solution because it involves reparsing form definitions to get their names, but changing the underlying JavaRosaParserWrapper is much riskier because more code depends on that.
Also, this change will become irrelevant once we have v2.0, so it feels like we wont' be running into much problems anyway.
There should be no changes in behavior due to this change.
Nope.
=> Issue #799 Fix getting form name for form keys

src/org/opendatakit/briefcase/reused/http/CommonsHttp.java, src/org/opendatakit/briefcase/reused/http/Request.java, src/org/opendatakit/briefcase/reused/http/RequestBuilder.java, src/org/opendatakit/briefcase/reused/transfer/CentralServer.java
Closes #801
Tested to push to Aggregate v2 (sandbox), Aggregate v1.17 in GAE, and Central (sandbox)
When pushing to Aggregate, I made sure to disable anonymous credentials to force Briefcase to use credentials and authenticate into the server.
In v1.16.3 we changed the cookie spec to IGNORE_COOKIES to work around an issue with multiple auth methods sent to Central servers. Doing so broke auth with Aggregate servers.
Since the cookie spec is set at an HTTP client level inside the executor, we can't create it each time we need to send a request because that would prevent requests to the same host to reuse connections. Having two executors (one with cookies, one without) is not an option either because it would leak too much of the internal workings.
Due to this, now we let the Request …
=> Issue #801 Restore cookies to interact with Aggregate

src/org/opendatakit/briefcase/export/ExportForms.java, src/org/opendatakit/briefcase/export/ExportToCsv.java, src/org/opendatakit/briefcase/model/form/FileSystemFormMetadataAdapter.java, src/org/opendatakit/briefcase/model/form/FormMetadata.java, src/org/opendatakit/briefcase/model/form/FormMetadataCommands.java, src/org/opendatakit/briefcase/pull/aggregate/PullFromAggregate.java, src/org/opendatakit/briefcase/pull/central/PullFromCentral.java, src/org/opendatakit/briefcase/ui/settings/SettingsPanel.java, src/org/opendatakit/briefcase/util/FormCache.java, test/java/org/opendatakit/briefcase/export/ExportToCsvScenario.java, test/java/org/opendatakit/briefcase/model/form/FileSystemFormMetadataAdapterTest.java, test/java/org/opendatakit/briefcase/model/form/FormMetadataCommandsTest.java, test/java/org/opendatakit/briefcase/model/form/FormMetadataQueriesTest.java, test/java/org/opendatakit/briefcase/model/form/FormMetadataTest.java
Closes #806
Fixed and run the automated tests
Manually pulled forms, changed the sd location, and exported them
This is the smallest change I could come up to be able to store relative paths while providing absolute paths to downstream code.
No risks here, just a fixed bug :)
Nope.
=> Issue #806 Metadata files should have relative paths

build.gradle, src/org/opendatakit/briefcase/export/ExportConfiguration.java, src/org/opendatakit/briefcase/export/FormDefinition.java, test/java/org/opendatakit/briefcase/CustomFunctionTest.java, test/resources/org/opendatakit/briefcase/custom-function-form.xml
Closes #796 
Use this form to test the PR: [custom-function-form.txt](https://github.com/opendatakit/briefcase/files/3604685/custom-function-form.txt)
Added an automated regression test
A brute force approach that used actual exception messages was considered to provide a quick&dirty solution that didn't require changes in JR, but we ultimately thought it was better to add a method in JR to provide fallback function handlers that would prevent the error from #796.
This should be a narrow change that only prevents the issue from #796
No.
=> Issue 796 support custom functions

src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java, src/org/opendatakit/briefcase/operations/PullFormFromCentral.java
Closes #812
In this PR
Testing of this PR involves this steps:
- Run the `-c` CLI op to clear all preferences
- Ensure the GUI environment is set and configured by running the GUI once and setting an sd
- Run a pull from Central CLI op
- Run the GUI again
In master, you are asked to set an sd for a second time, which shouldn't happen.
This is a super narrow fix. No other approaches were considered.
Somehow, setting the sd in the pull CLI ops was losing prefs for the GUI, and users were asked to set it again in the next GUI launch.
Also, setting the sd in CLI ops is not required (downstream code gets the briefcaseDir directly), so it's a safe change to do.
I tried to track uses of `BriefcasePreferences.getStorageDir()` in downstream code that would require the call to …
=> Issue 812 GUI fails to load after CLI used 

src/org/opendatakit/briefcase/push/central/CentralErrorMessage.java, src/org/opendatakit/briefcase/push/central/PushToCentralTracker.java
Closes: #821
All tests were executed succesfully.
=> fix: added toString for CentralErrorMessage

src/org/opendatakit/briefcase/pull/aggregate/OpaqueCursor.java, test/java/org/opendatakit/briefcase/model/form/FormMetadataCommandsTest.java
Closes #826 
Compile the project and run the tests
The proposed alternative versions feel straightforward. No other approaches considered.
This shouldn't change Briefcase behavior at all.
Nope.
=> Replace Java 11 API calls with Java 8 alternative calls

src/org/opendatakit/briefcase/model/BriefcaseFormDefinition.java, src/org/opendatakit/briefcase/model/OdkCollectFormDefinition.java, src/org/opendatakit/briefcase/util/BadFormDefinition.java
Closes #834
Test this PR with this JAR file: 
[briefcase_i834.zip](https://github.com/opendatakit/briefcase/files/3863403/briefcase_i834.zip)
Run automated tests
Straightforward change to enhance error logging.
No behavior changes in this PR.
Nope.
=> Provide causing exception to BadFormDefinition when available

src/org/opendatakit/briefcase/model/form/FileSystemFormMetadataAdapter.java
Closes #831
- Run automated tests
- Manually copied the form attached to #831 and verified that Briefcase can be launched
This is a straightforward change to ignore forms that can't be parsed while sync'ing files from the storage directory.
This should solve the issue. Users should expect a new log message "Couldn't parse form at /foo/ODK Briefcase Storage/forms/bar/bar.xml" each time Briefcase isn't able to sync a form for parsing reasons. The full stacktrace would include the causing error. In this case, having replaced the last `>` with a `?` character:
```
2019-11-19 15:25:57,597 [main] ERROR o.o.b.m.f.FileSystemFormMetadataAdapter - Couldn't parse form at /tmp/cocotero/ODK Briefcase Storage/forms/fieldListSimpleTest/fieldListSimpleTest.xml …
```
=> Issue 831 ignore failing forms on startup

src/org/opendatakit/briefcase/operations/Common.java, src/org/opendatakit/briefcase/operations/Export.java, src/org/opendatakit/briefcase/operations/ImportFromODK.java, src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java, src/org/opendatakit/briefcase/operations/PushFormToAggregate.java, src/org/opendatakit/briefcase/ui/BriefcaseCLI.java
Closes #824
Test it with this JAR: [briefcase_p833.zip](https://github.com/opendatakit/briefcase/files/3863090/briefcase_p833.zip)
- Run the automated tests
- Manually pulled forms from the sandbox using the CLI and providing relative paths in the `-sd` arg
Intercepting the value users provide as the storage directory while parsing CLI args feels like the smallest possible change and probably the safest place to do it.
Another approach would be to patch the particular place where the error was being produced, but that wouldn't get us rid of other similar undiscovered problems in other parts of the codebase.
The change will allow users to provide relative paths in the CLI. It shouldn't have unexpected behavior changes for users double-clicking the JAR file or manually launching the GUI …
=> Issue 824 relative paths in cli

src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java, src/org/opendatakit/briefcase/export/ExportConfiguration.java, src/org/opendatakit/briefcase/export/FormDefinition.java, src/org/opendatakit/briefcase/export/Model.java, src/org/opendatakit/briefcase/model/BriefcaseFormDefinition.java, src/org/opendatakit/briefcase/model/BriefcasePreferences.java, src/org/opendatakit/briefcase/model/TerminationFuture.java, src/org/opendatakit/briefcase/model/UpdatedBriefcaseFormDefinitionEvent.java, src/org/opendatakit/briefcase/model/form/FormKey.java, src/org/opendatakit/briefcase/pull/PullEvent.java, src/org/opendatakit/briefcase/reused/http/CommonsHttp.java, src/org/opendatakit/briefcase/reused/http/MultipartMessage.java, src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/CentralServerDialog.java, test/java/org/opendatakit/briefcase/reused/http/RequestSpyMatchers.java
* Reduce scope of members for issue #214
Closes #214 
Code compiles and tests pass
Used IntelliJ's code inspection to find members that could be changed to a more restrictive scope.
None
No
=> Reduce scope of members

src/org/opendatakit/briefcase/ui/export/components/ExportFormsTableView.java, src/org/opendatakit/briefcase/ui/export/components/ExportFormsTableViewModel.java, src/org/opendatakit/briefcase/ui/reused/ButtonProcessing.java, src/org/opendatakit/briefcase/ui/reused/DetailsStatusButton.java, src/org/opendatakit/briefcase/ui/reused/ExportConfigurationButton.java, src/org/opendatakit/briefcase/ui/reused/UI.java, src/org/opendatakit/briefcase/ui/reused/transfer/TransferFormsTableView.java, src/org/opendatakit/briefcase/ui/reused/transfer/TransferFormsTableViewModel.java
Closes #838 
Tested using UI for all buttons and chevrons. 
Created classes called DetailsStatusButton and ExportConfigurationButton. The selection column didn't need a class for it as there was no business logic incorporated. So we continued to use a compareSelectionfunction inside the UI class.
Localized just to the UI tests conducted.
No
=> Buttonclass

src/org/opendatakit/briefcase/ui/pull/PullPanel.java
The bug was caused by the fact that the Source/Target panel has no information that the forms are being loaded from the server. Making a call to setWorking() in the current view makes the buttons in the Source/Target panel to go disabled until the unsetWorking method is call. I think this fixes the bug as the user won be able to click on reset (or reload) during the time the forms are being loaded, and also the user will have good feedback.
Closes #
I was able to reproduce the bug before the fix, after the fix i cannot hit the reset button while loading.
It uses the already created method setWorking that is intended for this kind of behavior
The user won be able to cancel the form loading process, but i think that is ok.
I dont think this need to be put explicitly in the documentation as …
=> A solution for Bug #798

src/org/opendatakit/briefcase/reused/http/CommonsHttp.java
Make HTTP post requests repeatable by wrapping entities into a repeatable entity
In order to test this PR with Ona servers, https://stage-odk.ona.io must be used because it looks like the production servers haven't been patched yet.
Closes #852
@DavisRayM has tested that this PR fixes the issues he's experiencing while pushing forms to Ona.
The changes in this PR come straight up from Apache HttpClient's documentation & examples, so no alternatives have been considered.
The change is super narrow, so I don't expect any nasty side-effects, although manual tests should be extended to Aggregate and Central servers just to be sure nothing broke.
Nope.
=> Make HTTP POST requests repeatable

src/org/opendatakit/briefcase/export/FormDefinition.java, test/java/org/opendatakit/briefcase/export/ExportToCsvExplodeRandomizedChoiceListTest.java, test/resources/org/opendatakit/briefcase/export/choice-lists-randomize-submission.xml, test/resources/org/opendatakit/briefcase/export/choice-lists-randomize.csv.expected, test/resources/org/opendatakit/briefcase/export/choice-lists-randomize.xml
Closes #862
Wrote and ran automated test. I also used the form linked in the issue discussion to send real submissions and verify the behavior at the command line with the smart append feature. However, the problem really ended up being just about the interaction with choice list randomization and the split select multiples feature.
The way that choice list randomization is implemented in JavaRosa is admittedly a hack. It's the best we could come up with at the time and I took advantage of that approach to ensure that the randomization never happens when using Briefcase. I don't love that this means I'm using a public boolean field on `ItemsetBinding` but I don't see an alternative and I think it can be revised if ever the JavaRosa implementation is improved.
The only intended change is …
=> Never randomize choice lists to ensure stable export order

README.md, src/org/opendatakit/briefcase/push/central/PushToCentral.java, src/org/opendatakit/briefcase/push/central/PushToCentralTracker.java, src/org/opendatakit/briefcase/reused/transfer/CentralServer.java, test/java/org/opendatakit/briefcase/push/central/PushToCentralTest.java
Closes #860
Updated the relevant test and did manual testing against https://sandbox.central.opendatakit.org/.
Initially I thought I'd try to support all versions of Central but I decided that it's not worth it. It's relatively easy to upgrade Central and users really shouldn't be running on old versions. As far as we know there's no behavior that was deprecated that would require users to stay on pre-0.8. I did try to give a useful error message in case of trying to push to an older Central so users can recover.
In terms of code structure, I tried to follow existing patterns as much as possible.
The first commit isn't entirely related but it came up because I was going to lower the level of some errors that are showing up in Sentry but then I realized that they weren't intended to show …
=> Push Central attachments to draft endpoint and publish draft

src/org/opendatakit/briefcase/reused/transfer/CentralServer.java, test/java/org/opendatakit/briefcase/reused/transfer/TransferTestHelpers.java
Closes #861 
Added a draft form definition to Central project, configured that project as a pull source, verified that the draft form didn't show up in the list.
This filters out drafts which is exactly what we want. I don't see any other possibilities.
It should just fix the bug. It's a one line change that's very targeted so should truly be very low risk.
No.
=> Exclude draft form definitions from Central list

src/org/opendatakit/briefcase/reused/http/Request.java, test/java/org/opendatakit/briefcase/reused/http/RequestTest.java
Closes #880
Ran it with the form from the issue, wrote an automated test. I also pushed that same form and exported it to confirm there were no other issues with a form id with a space.
I initially thought I could use some kind of Java API for this but I don't think so. See https://stackoverflow.com/questions/4737841/urlencoder-not-able-to-translate-space-character. I decided to be very surgical and only handle spaces for now and we can deal with other characters that need to be URI-encoded if they actually come up.
The only thing this does is replace spaces in URIs with `%20`. It should be very safe.
No.
=> URI-encode spaces in URLs

src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java, src/org/opendatakit/aggregate/parser/MediaFileReferenceFactory.java, src/org/opendatakit/briefcase/model/BriefcaseFormDefinition.java, src/org/opendatakit/briefcase/util/FileSystemUtils.java, src/org/opendatakit/briefcase/util/JavaRosaParserWrapper.java, test/java/org/opendatakit/briefcase/model/BriefcaseFormDefinitionWithExternalDataTest.java, test/resources/org/opendatakit/briefcase/model/external-xml.xml, test/resources/org/opendatakit/briefcase/model/form-with-external-secondary-instance.xml
Needed to build a FormDef for files with external secondary instances.
Closes #878
Wrote a test that fails with the user-reported error on master. Tried downloading a real form with external secondary instances and then exporting it. @getodk/testers I think it would be good to try with some of the other ones that you have with both xml and csv external instances and a few submissions.
The core of the solution is setting up a `ReferenceFactory` for the singleton `ReferenceManager`. I don't see any alternatives to that. The decision points I saw were around where to actually build the media directory paths and how much of the `ReferenceFactory` to implement. It felt reasonable to make `getMediaDirectory` public and `JavaRosaWrapper` and `BriefcaseFormDefinition` call it.
For the …
=> Resolve all jr:// URIs to media directory

src/org/opendatakit/briefcase/export/ExportToCsv.java, src/org/opendatakit/briefcase/export/SubmissionParser.java
Closes #874
Tried different exports with and without empty submission.xml files. Clearing the contents of a submission.xml file reproduces the original issue. With this PR, the export should be successful, there should be a message in the details saying `Can't export submission ...`, the `-errors` folder should include the failed submission with its instanceID.
This is the only solution I considered once I realized that submissions that were leading to parse errors were included in the submissions to export. This is the simplest way to exclude those submissions.
Users should get fewer export errors and should have more information to recover from them when they do happen. The regression risk is low because it only affects the path where there's an exception on parse.
No.
=> On export, skip submissions that can't be parsed

src/org/opendatakit/briefcase/pull/aggregate/PullFromAggregate.java, src/org/opendatakit/briefcase/pull/central/PullFromCentral.java, src/org/opendatakit/briefcase/pull/central/PullFromCentralTracker.java, test/java/org/opendatakit/briefcase/pull/central/PullFromCentralIntegrationTest.java, test/java/org/opendatakit/briefcase/pull/central/PullFromCentralTest.java, test/java/org/opendatakit/briefcase/reused/transfer/TransferTestHelpers.java
Closes #886
Prior to this change, submissions whose instanceIDs were in the instance database were filtered out when doing a pull from Central. The problem is that presence in the db does not mean any file was successfully saved for that instance. One change I made to address this is to not save an instanceID to the database if the pull task has been cancelled. **I made this change to pull from Aggregate as well.** What this should mean is that if a pull is cancelled, the submission(s) that are being downloaded at the time should not be skipped on a subsequent pull.
For Central, I also changed when the database is checked for an instance. Prior to this change, if an instanceID were in the database, the submission would be skipped entirely. Now, if the submission is in the database, we:
- …
=> When pulling from Central, download submission or attachment files that don't exist
